dist/entry.js
src/parser/js.js
src/parser/parser.js
src/workspace/vim.js
src/workspace/workspace.js

add error check logic

---

dist/entry.css
src/css/entry.less

change ws playground view like art view

---

extern/util/handle.js

modified object center circle size from 7 to 5

modified object center circle size from 7 to 5

---

dist/entry.js
extern/util/static.js
src/project.js

entry 와함께 반영 부탁 드립니다. 
block lang 변경된 부분 fix 입니다.

Entry lang change

---

dist/entry.js
src/hw.js
src/hw_monitor.js

revert neobot

---

dist/entry.css
dist/entry.js
src/blocks/block_albert.js
src/blocks/block_arduino.js
src/css/components/hw_monitor.less
src/hw.js
src/hw_monitor.js
src/property_panel.js

change lang

---

src/hw.js

hw_upgrade_1.5.1

---

src/workspace/block_entry.js

boolgom/Entry/pull/2677 과 함께 반영

offline 인지 체크 하여 블록 명칭 변경하도록 수정.

---

src/blocks/block_arduino.js
src/workspace/block_entry.js

modify dplay block

---

src/blocks/block_arduino.js
src/workspace/block_entry.js

modify block

---

src/workspace/block_entry.js

bitbrick servo fix

---

src/blocks/block_hamster.js

change hamster template

---

dist/entry.css
src/css/components/property_panel.less

클래스명이 중복으로 들어가 올바른 이미지가 나오지 않았습니다~

close #3206

---

src/workspace/block_entry.js

https://github.com/boolgom/Entry/issues/3462

temp commit

---

extern/util/static.js

하드웨어 오프라인등에서 require형태로 사용할수 있도록 exports 옵션에 EntryStatic 추가

add export option 'EntryStatic'

---

dist/entry.js
src/container.js

origin https://github.com/boolgom/Entry/issues/3857
ref https://github.com/boolgom/Entry/issues/3977
** 로컬 리스트를 다른 오브젝트에서도 접근 가능한 버그 해결

local list dropdown bug

---

src/workspace/block_entry.js

ref https://github.com/boolgom/Entry/issues/3994
origin https://github.com/boolgom/Entry/issues/3670
** 삼각함수 값이 부정확하게 반환되는 버그 픽스

do not cut value

---

dist/entry.css
src/css/components/popup.less

issue #4068 
메이즈 도움말 팝업 개선 작업입니다.

help popup

---

extern/util/static.js

Entry 쪽 PR #4938 와 함께 반영되어야 합니다.
최근 좋아요를 많이 받은 작품 : 최근 3일간의 좋아요 수를 기준으로 내림차순

[pc웹] 공유하기 > 작품 공유하기 필터 기능 점검 필요 #3705

---

extern/util/static.js
src/hw.js
src/workspace/block_entry.js

Jeil science smartBoard blocks added

---

extern/util/static.js
src/workspace/block_entry.js

로보티즈 새블록 추가(로보티즈에서 테스트 완료)
ref boolgom/Entry#4116

로보티즈 블록 추가

---

dist/entry.css
src/css/components/context_menu.less

ref https://github.com/boolgom/Entry/issues/4339
**i.e에서 장면 복제하기 컨텍스트 메뉴 깨지는 현상 해결

contetemnu zIndex edited

---

extern/util/static.js
src/workspace/block_entry.js

boolgom/Entry#5105
블록 명칭 변경 및 클라우드 PC관련 블록 추가

#5105 이슈 블록 추가.

---

src/workspace/block_entry.js

@chanlee 아두이노 확장 모드에서 무음처리시 오류가 발생하는것을 처리 하였습니다.

톤블록 무음 처리 오류 수정.

---

dist/entry.css
dist/entry.js
src/css/components/playground.less
src/playground.js

ws 글상자 > 브라우저 화면 줄일 경우에 폰트, 배경 색상 UI 밀림 현상 이슈입니다.
absolute로 들어가 있는데 해당 속성의 돔 위치가 잘못 들어가 있어서, 화면이 줄어들 때에 부모를 따라가지 못해서 발생했습니다. dom 수정했습니다.
그리고 이슈 해결 중에, 글상자 추가 모달에서 색상 선택 창 위치가 밀려있는 것을 발견하여 함께 수정했습니다.

fix fonts, bg color ui

---

example/example.html

하드웨어 업체이슈.
example.html에 codemirror 라이브러리가 존재하지 않아 제대로 페이지가 뜨지 않음.
조치
codemirror cdn js 등록 처리

add codemirror

---

src/workspace/block_entry.js

issue #5648
https://github.com/boolgom/Entry/pull/5700

issue #5648

---

example/example.html

fix boolgom/Entry#5788
하드웨어 업체 전달용 소스(example.html) 수정

socket.io 주소 변경

---

src/workspace/block_entry.js

boolgom/Entry#5579 
코드이노와 ev3 영문 추가(entry 와 같이 반영)

Issue/5579 (3.1.0 마일스톤)

---

src/workspace/block_entry.js

boolgom/Entry#5864
코블 하드웨어 소스 누락건입니다.
3.1.0 때 같이 반영되면 좋을것 같습니다.

fix issue 5864

---

src/workspace/block_entry.js

엔트리 프로젝트를 저장할 때 , options: Entry.Chocopi.portlist  속성을 읽지 못해서 오류가 발생하네요.
그래서 리스트를 그냥 풀어 넣었습니다.

save failure problem solved

---

src/init.js

disable flash audio plugin

---

src/painter.js
src/painter2.js

issue 6859

---

src/playground.js

boolgom/Entry#6868 처리
영문에서 초 -> " 로 변경

issue 6868

---

src/project.js

ref https://github.com/boolgom/Entry/issues/6865
** [WS 공통]Block > Calculate > timer블록 조립 > 실행창에 초시계로 노출됨
ref https://github.com/boolgom/Entry/issues/6866
** [WS 공통] Block > Variable > response블록 조립 > 대답으로 노출됨

basic project lang

---

src/helper.js
src/workspace/block_entry.js

ref https://github.com/boolgom/Entry/issues/6879
** [WS 공통] Attribute > Function > Add function > 도움말에서 블록명이 한글로 노출됨

function help lang

---

src/workspace/block_entry.js

boolgom/Entry#4493 이슈 처리
변경할 값에 float 형으로 숫자를 작성하면 소수점 둘째 자리 까지 표현하도록 변경함.

이슈 4493 처리

---

src/workspace/block_menu.js
src/workspace/board.js

ref https://github.com/boolgom/Entry/issues/4996
** [WS] Win10 > 크롬 > 시작 카테고리 블록 공백 노출
* * 3.5.0

add event listener for font load

---

dist/entry.css
src/css/components/helper.less

ref https://github.com/boolgom/Entry/issues/7062
** [PC웹] 오픈 강의 > 강의 > WS > 도움말 영역 > 블록 위로 여백 없음

[3.5.0] lecture helper block css

---

src/variable.js

ref https://github.com/boolgom/Entry/issues/4148
** [ws] 변수명이 긴 경우 슬라이더의 max값에 가까운 값을 슬라이더로 입력할 수 없음 
** 3.5.0

slide float point value

---

src/function.js
src/workspace/block_view.js

ref https://github.com/boolgom/Entry/issues/5402
** [CS] > 함수안에 파라미터가 다수 등록시 블록이 깨지는 현상

[3.5.0]block template bug fix

---

src/container.js
src/engine.js
src/entity.js
src/object.js
src/stage.js

ref https://github.com/boolgom/Entry/issues/5240
** [ws] IE 에서 복제본 생성 작품 실행 시 퍼포먼스 저하 발생
** 3.5.0

container image caching

---

src/container.js
src/scene.js

ref https://github.com/boolgom/Entry/issues/5143
** [ws] 장면 복제 시 오브젝트 복제 관련 선택지 유지
** 3.5.0

clone scene adjust object ids

---

src/workspace/block_entry.js

removed dc motor block by jkemc

removed dc motor block by jkemc

---

src/variable.js

ref https://github.com/boolgom/Entry/issues/5547
** [ws] 리스트 뷰어 키 값 가로 길이에 따라 말줄임 적용

[3.5.0] list value trunc

---

extern/util/CanvasInput.js
src/stage.js
src/util/utils.js

ref https://github.com/boolgom/Entry/issues/7089
** [WS/모바일] 아이패드 > 묻고대답기다리기 블록 실행 > 대답 입력 불가능
** 3.5.0

mobile friendly for canvasInput

---

src/project.js

- https://github.com/boolgom/Entry/pull/7081 와 함께 반영 필요

issue #7058 Entry/issue/#7058 관 연관이슈. 프로젝트 초기화시 언어 지원추가

---

src/hw.js

@chanlee 
ino파일 다운로드 경로 변경 해서 올렸습니다.

ino 파일 다운로드 경로 변경

---

dist/entry.css
src/class/model.js
src/core/svg.js
src/css/components/board.less
src/playground.js
src/workspace/block_view.js
src/workspace/board.js
src/workspace/field/block.js
src/workspace/field/dropdown.js
src/workspace/field/dropdownDynamic.js
src/workspace/field/field.js
src/workspace/field/indicator.js
src/workspace/field/statement.js
src/workspace/field/text.js
src/workspace/field/textInput.js
src/workspace/skeleton.js

ref https://github.com/boolgom/Entry/issues/5373
** [IE] 블록이 많은 오브젝트 선택시 딜레이 및 마우스포인터에 오브젝트가 붙는 현상

[3.5.0] Issue/block render

---

src/variable_container.js

ref https://github.com/boolgom/Entry/issues/6995
** https://github.com/boolgom/Entry/issues/6995

[3.5.0] add ref remove ref

---

.jshintrc
src/workspace/workspace.js

ref https://github.com/boolgom/Entry/issues/7179
** [PC웹] 학습하기 > 미션 해결하기 > 로봇 공장 > 자바스크립트 모드로 전환 > 오브젝트가 존재하지 않는다는 알럿 노출됨

[3.5.0] check playground before check object

---

src/hw.js

boolgom/Entry#7220 
@chanlee @boolgom 
하드웨어 1.6.12 배포 입니다.

하드웨어 1.6.12 배포

---

src/container.js
src/engine.js
src/entity.js
src/scene.js
src/stage.js

ref https://github.com/boolgom/Entry/issues/7121
** [ws] 선택된 장면을 "장면 시작하기" 블록으로 시작시 반복하기 블록이 중복 실행됨

[3.6.0] reset scene when select current

---

src/container.js
src/engine.js

ref https://github.com/boolgom/Entry/issues/2966
** [WS] 장면이동시 입력창 종료되도록 하기

[3.6.0] reset canvas inputField when reset scene

---

src/entity.js

issue/3558 reopen. 폰트크기에 따른 높이 설정.

---

src/playground.js

- entryjs 하위 static 이미지 다운로드 주소 변경.(url -> 다운로드)
- https://github.com/boolgom/Entry/issues/7258

entryjs static image download

---

src/workspace/block_entry.js

@chanlee @boolgom 
금일 하드웨어 핫픽스 입니다.

xbot_buzzer 수정

---

extern/util/static.js
src/blocks/block_codestar.js
src/workspace/block_entry.js

이산솔루션 코드스타 tilt블록 추가, 오타 정정 및 센서 포트번호 변경되었습니다.

Edit Codestar sensor port number

---

extern/util/static.js
src/textcoding/parser/core/text/pyToBlock.js
src/workspace/block_entry.js

ref https://github.com/boolgom/Entry/issues/3533

[3.7.0] boolean_and_or

---

src/textcoding/util/textCodingUtil.js

ref https://github.com/boolgom/Entry/issues/7312
** [파이선] 블록 -> 파이선 모드 전환 시, 함수 관련 알럿 메시지가 잘 못 노출됨

[3.7.0] python function convert error bug fix

---

src/workspace/block_view.js
src/workspace/field/angle.js
src/workspace/field/block.js

ref https://github.com/boolgom/Entry/issues/7279
** [파이썬] 블록 꾸러미에 있는 "참" 블록을 True 로 대체

[3.7.0] textMode fieldBlock render bug

---

src/workspace/field/field.js

ref https://github.com/boolgom/Entry/issues/7285
** [PC웹]코스웨어>따라하기>드롭다운 영역 클릭에 따른 말풍선 출력 오류

[3.7.0] field bind duplicated event bug fix

---

src/textcoding/parser/core/block/blockToPy.js

ref https://github.com/boolgom/Entry/issues/7304
** [파이선] 드래그&드롭으로 삽입할 수 없는 함수 검토 요청

[3.7.0] function data check

---

src/variable.js

casting to Number before toFixed

casting to number

---

extern/util/filbert.js
src/textcoding/parser.js

resolve issue

---

src/workspace/block_entry.js

[3.7.0] boolean_and_or block def and isNotFor check

---

src/blocks/block_byrobot_petrone_v2_drive.js

수정사항 입니다. (오작동 해결)

---

src/variable.js

boolgom/Entry#6431 에 관한 이슈입니다.

change number policy

---

src/variable.js

change position

---

src/blocks/block_codestar.js
src/workspace/block_entry.js

코드스타 블록 이름 변경

---

src/util/utils.js
src/variable.js

https://github.com/boolgom/Entry/issues/7486
** [WS] > 특정 작품 실행 > X축, Y축 값이 운영에서와 다르게 노출됨

[3.7.0] integer check

---

src/workspace/block_entry.js

https://github.com/boolgom/Entry/issues/7489
** [WS] > 도움말 > 참 그리고 참, 참 또는 거짓 블록의 도움말이 노출되지 않음

[3.7.0] python def

---

src/variable_container.js

https://github.com/boolgom/Entry/issues/7306
** [WS] WS > 지역변수로 변수 선언 > 오브젝트/장면 복제 > 변수명이 똑같이 복제됨

[3.8.0] local variable name check

---

src/container.js

https://github.com/boolgom/Entry/issues/7254
** [WS] '엔트리봇_걷기2' 모양으로 바꾸기 블록 조립 > 엔트리봇 복제 > 복제된 블록에는 '대상 없음'으로 노출됨

[3.8.0] adjust values when clone object

---

src/workspace/block_entry.js

https://github.com/boolgom/Entry/issues/4778
** [pc 웹] 강의 생성 2단계에서 선택하지 않은 카테고리 자동 노출됨

[3.8.0] button defs

---

extern/lang/code.js
extern/lang/en.js
extern/lang/ko.js
extern/lang/vn.js
extern/util/static.js
src/blocks/block_arduino.js
src/hw.js
src/workspace/block_entry.js

memaker added by JKEMC

---

extern/lang/code.js
extern/lang/en.js
extern/lang/ko.js
extern/lang/vn.js
extern/util/static.js
src/blocks/block_arduino.js
src/workspace/block_entry.js

lcd block modified

---

src/textcoding/parser/core/text/pyToBlock.js

issue 7459

---

src/engine.js
src/workspace/workspace.js

https://github.com/boolgom/Entry/issues/7496
** [WS] 파이선 강의 > 코드 입력 > 강의WS 종료 > 재진입 > 팝업 노출 안됨

[3.8.0] workspace text code event

---

src/class/event.js
src/engine.js
src/function.js
src/painter2.js
src/playground.js
src/property_panel.js
src/util/contextmenu.js
src/workspace/block_menu.js
src/workspace/block_view.js
src/workspace/board.js
src/workspace/code.js
src/workspace/field/angle.js
src/workspace/field/dropdown.js
src/workspace/field/field.js
src/workspace/field/keyboardInput.js
src/workspace/field/statement.js
src/workspace/workspace.js

https://github.com/boolgom/Entry/issues/7481
** [ws] 작품 실행 중 "수정사항 저장 여부" 묻는 현상

[3.8.0] event control for painter

---

.jshintrc
src/container.js
src/entry.js
src/object.js
src/workspace/block_menu.js
src/workspace/board.js
src/workspace/scroll.js
src/workspace/thread_view.js
src/workspace/workspace.js

https://github.com/boolgom/Entry/issues/7277
** [ws] 모든 오브젝트 없는 상태에서 저장 버튼 클릭 시 오류 발생

[3.8.0] check objects length when exporting project

---

src/command/commands/container.js
src/container.js

boolgom/Entry#7642
오브젝트가 화면 바깥에 있을 시 오브젝트 뷰로 스크롤

issue 7642

---

src/textcoding/parser.js

issue 7650

---

src/textcoding/parser.js

hotfix for maze

---

src/workspace/block.js
src/workspace/block_entry.js
src/workspace/block_menu.js
src/workspace/block_view.js
src/workspace/extension/guide.js
src/workspace/extension/side_tag.js
src/workspace/field/block.js
src/workspace/field/dropdown.js
src/workspace/field/dropdownDynamic.js
src/workspace/field/field.js
src/workspace/field/indicator.js
src/workspace/field/output.js
src/workspace/skinner.js

https://github.com/boolgom/Entry/issues/7617
** [WS] > 함수 만들기 > 함수, 이름 블록이 복사와 붙여넣기 동작 가능
** 함수 첫번째 파라미터 삭제시 디폴트 파라미터로 채워지지 않는 버그 해결

function param copyable

---

src/textcoding/parser/core/block/blockToPy.js

boolgom/Entry#7834
https://github.com/boolgom/Entry/issues/5270 사이드 이펙트
함수 파라미터 블록을 제외함으로서 해결

hotfix 7834

---

src/container.js
src/object.js
src/util/utils.js

https://github.com/boolgom/Entry/issues/7808
** [WS] > 오브젝트 옆 연필 모양 클릭(오브젝트명 수정) > 백스페이스키 누름 > 페이지 나가기로 동작

select input field

---

src/textcoding/hint/python.js

this resolve issue boolgom/Entry#7309

issue 7309

---

extern/util/filbert.js
src/textcoding/hint/python.js

issue/5448 Remove octal number processing

---

src/workspace/board.js

https://github.com/boolgom/Entry/issues/7688
** [ws] 함수 확인/취소 버튼 위치 변경

overlay buttons align

---

src/workspace/block_entry.js
src/workspace/field/block.js

fix issue boolgom/Entry#3384

---

src/object.js

https://github.com/boolgom/Entry/issues/2955
** [WS] 회전방식 변경시, 이동방향을 리셋하지 않고 유지하기
** 1157 line이 이슈와 관련 코드이고 나머지는 정리 코드

maintain object direction

---

src/command/commands/object.js
src/object.js
src/util/static.js
src/workspace/block_menu.js
src/workspace/block_menu_scroll.js

https://github.com/boolgom/Entry/issues/7882
** [WS] 오브젝트명 수정 후 새로만들기 기능 실행 시 작품 저장 여부를 묻지 않음

object name edit command

---

src/object.js
src/workspace/field/field.js
src/workspace/field/textInput.js

https://github.com/boolgom/Entry/issues/7957
** [코스웨어] 따라하기 > 텍스트 입력 > 딤드 영역 클릭 시 다음 단계로 넘어가도록하는 이슈

field text input applyValue when blur

---

src/workspace/block_entry.js

https://github.com/boolgom/Entry/issues/7789
** [WS] 코드 멈추기 블록 > '다른 오브젝트의' 옵션 추가

stop other object

---

src/entity.js

boolgom/Entry#8122 
underline -> underLine 으로 교체
대소문자 차이로 처음 오브젝트 등록할때 밑줄이 정상적으로 동작 안함.

이슈 #8122 처리

---

src/workspace/block_entry.js

boolgom/Entry#8149 이슈 처리
boolgom/Entry#8246 PR과 함께 적용 필요.
메이플 메이즈 점프 블록 다국어 적용.

#8149 이슈 처리

---

src/workspace/block_entry.js

boolgom/Entry#8149 
hidden_loop 블록 다국어 적용.

hidden_loop 블록 다국어 적용.

---

src/workspace/block.js
src/workspace/block_menu.js
src/workspace/field/block.js
src/workspace/thread_view.js

https://github.com/boolgom/Entry/issues/8263
** [ws] 작품 블록 데이터 오류

replace undefined block to default block

---

src/workspace/block_entry.js

boolgom/Entry#8149
@boolgom 
누락된 번역 적용.

change jump block lang

---

src/workspace/block_entry.js

issue 8029

---

extern/util/static.js
src/workspace/block_entry.js

add get_user_name block

---

src/blocks/block_arduino.js

edit block_arduino

---

src/playground/block_menu.js
src/playground/block_view.js
src/playground/board.js
src/util/contextmenu.js
src/util/utils.js

https://github.com/boolgom/Entry/issues/8441
** [WS] 파이선/블록 모드 블록 > 마우스 우클릭 > 이미지로 저장하기 기능 추가

blockMenu download image

---

src/playground/blocks/block_arduino.js
src/playground/blocks/block_arduino_ext.js
src/playground/blocks/block_arduino_nano.js
src/textcoding/parser/core/block/blockToPy.js

boolgom/Entry#8447
8447 이슈 처리
아두이노/ 아두이노 확장 에서 파이선 명령어인 Arduino.digitalRead() 사용시 
연결된 하드웨어에 따라 아두이노와 아두이노 확장 모두 기능이 동작하도록 변경

issue 8447

---

src/class/container.js
src/class/scene.js

boolgom/Entry#8423
장면 복제/삭제시 불필요한 작업 최소화

이슈 8423 처리

---

src/class/playground.js

issue #8557 
https://github.com/boolgom/Entry/issues/8557
기본 모양(소리) 다운로드 오류

issue #8557

---

src/class/variable.js

https://github.com/entrylabssecret/Entry/issues/8432
[WS] 변수 아이콘 노출 위치 확인 요청

variable list position bug fix

---

src/playground/code.js
src/playground/executors.js
src/util/utils.js

https://oss.navercorp.com/entry/Entry/issues/3529
** [pc 웹] 메이즈에서 실행중인 블록 강조

maze focus execution block

---

src/class/object.js

[#8544](https://oss.navercorp.com/entry/Entry/issues/8544) 이슈처리
textBox 옵션 세팅을 좀더 유연하게 변경함.

update textBox setting

---

package-lock.json
src/playground/blocks/block_neobot.js

안녕하세요. 코딩로봇연구소 이민준입니다.
block_neobot -> 네오봇 다국어 지원을 위해서 변경한 소스코드에 대해서 pull request 합니다.
감사합니다.

block_neobot 다국어 지원

---

extern/util/static_mini.js

https://oss.navercorp.com/entry/Entry/issues/8672
** [WS] 실과 WS > 움직임 > []초 동안 x:[] y:[] 만큼 움직이기 블록 추가 요청

add move_xy_time block to static_mini.js

---

.idea/vcs.xml
extern/lang/en.js
extern/lang/ko.js
extern/util/static.js
src/playground/blocks/block_coding_box.js
src/playground/blocks/index.js

"코딩박스"라는 아두이노 기반 피지컬컴퓨팅 학습 도구입니다. 등록 요청드립니다

코딩박스 등록요청합니다.

---

extern/util/static.js

https://oss.navercorp.com/entry/Entry/issues/8673

remove discuss category

---

src/util/utils.js

https://oss.navercorp.com/entry/Entry/issues/8752 
- 마우스 스크롤 offset return

hotfix. return mouse pointers

---

src/playground/block_view.js

https://oss.navercorp.com/entry/Entry/issues/8751

mobile longpress bug fix

---

src/textcoding/parser/core/block/blockToPy.js

함수 안에서 다른 함수를 사용할 시, 특히 루프 불록 안에서 사용시 함수 명세가 제공되지 않았던 점 수정.

issue 8794 fix

---

src/playground/field/keyboardInput.js

https://oss.navercorp.com/entry/Entry/issues/8748 이슈처리

issue 8748 처리

---

src/textcoding/parser/core/block/blockToPy.js

https://oss.navercorp.com/entry/Entry/issues/8804

issue 8804

---

src/playground/block_menu.js

https://oss.navercorp.com/entry/Entry/issues/8813
@chanlee 코스웨어 수정입니다.

issue 8813처리

---

extern/util/static.js
src/playground/block.js
src/playground/blocks/block_start.js

https://oss.navercorp.com/entry/Entry/issues/8811#event-7126468

양수, 음수 체크 블록 추가

---

src/command/commands/block.js
src/playground/block_menu.js
src/playground/field/block.js

https://oss.navercorp.com/entry/Entry/issues/8812 처리
@chanlee  코스웨어 이슈 입니다.

이슈 8812 처리

---

src/class/engine.js

targetChecker가 없는 경우에 clearListener 실행 안하도록 변경

8819 오류 처리

---

.babelrc
.prettierrc
package.json
src/command/commands/container.js
webpack_config/common.js
yarn.lock

https://oss.navercorp.com/entry/Entry/issues/8842
$$hashkey를 지우는 로직때문에 기존 font 정보가 사라지는 문제수정

issue 8842처리

---

src/playground/field/dropdown.js
src/playground/field/dropdownDynamic.js

https://oss.navercorp.com/entry/Entry/issues/8861 처리
case1과 case2의 경우는 일단 현재 개발된 스펙이 따로 작성하도록 되어 있어 사용방법을 가이드 하였고
case3인 드롭다운 선택과 관련해서만 수정하였습니다.

이슈 8861 처리

---

src/class/container.js

https://oss.navercorp.com/entry/Entry/issues/8875
핫픽스 건

issue 8875 처리

---

src/class/variable_container.js

https://oss.navercorp.com/entry/Entry/issues/8880
https://oss.navercorp.com/entry/Entry/issues/8876
두개 이슈 처리 입니다.
clearProject 수행할때 속성 선택도 all로 다시 세팅해주도록 수정하였습니다.

이슈 8880 처리

---

src/playground/blocks/block_bitbrick.js

비트브릭 진동센서, 초음파 센서추가, setLanguage 추가

비트브릭 진동센서, 초음파 센서추가, setLanguage 추가

---

src/playground/block_menu.js

https://oss.navercorp.com/entry/Entry/issues/8981

이슈 8981 처리

---

src/css/components/variable_container.less

리스트 import / export font-size -1 (IE 대응)

---

src/class/container.js
src/class/project.js
src/command/commands/object.js
src/util/utils.js

[#9042]  날씨 블록 초기화 로직 변경

---

src/playground/blocks/block_bitbrick.js

setLanguage sensor_value 항목을 수정했습니다.

bitbrick setLanguage sensor_value change

---

src/playground/blocks/block_roborobo.js

Merge 3.18.0 from develop-hw

---

src/playground/blocks/block_expansion_weather.js
src/util/weather_forecast.js

날씨블럭 async 수정

---

src/playground/blocks/block_dash.js

Reverts entrylabs/entryjs#1033

Revert "대시 수정 사항"

---

extern/util/static.js
src/playground/blocks/block_truerobot.js

뚜루뚜루 블럭 추가

---

src/class/engine.js
src/class/variable.js

* Issue : https://oss.navercorp.com/entry/Entry/issues/8858
* Entry PR : https://oss.navercorp.com/entry/Entry/pull/9150?w=1
* 내용
* 작품 stop, pause 이벤트에 dispatchEvent 추가
* Entry.variableContainer.variable cloudDate get, set 추가

[WS] 공유리스트/변수 저장 방식 변경 #8858

---

src/playground/blocks/block_hummingbird.js

- 허밍버드 듀오(Hummingbird Duo) 소리센서, 온도센서, 거리센서 수정

허밍벚드 듀오 센서 디스플레이 값 변경

---

package.json
src/playground/block_view.js
webpack_config/prod.js

hasIn 의 내부 로직이 'key in Object(target)' 형태로 simplify 되면서 deep find 가 정상적으로 동작하지 않아 사용되는 함수 수정

[issue/9132] 재귀식 변수명 reDraw 함수 수정

---

src/playground/field/dropdownDynamic.js

[#9233]  dynamic dropdown  오프라인 로드시 값 불오는부분 수정.

issue 9233 처리

---

src/playground/block_view.js

[CS][PC웹] 학습하기 > 조석 가위바위보 학습 시 에러 발생 #9320

---

src/playground/blocks/block_start.js

1. block_start.js pre 명칭 수정
-pre -> prev 로 수정

Issue/9519 엔트리파일썬 명칭수정

---

src/util/common.js
src/util/weather_forecast.js

- expansionBlocks의 url을 api변수로 통일.
- Entry Offline 관련하여 url 변경부분 추가.

Entry Offline 관련하여 url 변경 추가.

---

src/playground/blocks/block_expansion_behaviorconduct_disaster.js
src/playground/blocks/block_expansion_behaviorconduct_lifesafety.js
src/playground/blocks/block_expansion_festival.js
src/playground/blocks/block_expansion_translate.js
src/playground/blocks/block_expansion_weather.js

Issue/9755 확장블럭 일본어 타이틀 텍스트 추가

---

src/playground/blocks/block_calc.js

Issue/9872 ['안녕 엔트리!' 의 '안녕' 을(를) '반가워' 로 바꾸기]  블럭 수정
https://oss.navercorp.com/entry/Entry/issues/9872
1. block_calc.js
- script.getStringValue('OLD_WORD', script)  특수문자 replace 처리 .. .replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

Issue/9872 

---

src/class/scene.js

- clear시 html으로 삭제하여 동기화 되지 않앗음.
- clearProject 이후 바로 로드시 오류발생으로 setTimeout을 이용하여 queue로 순차 실행하도록.

[#9133] Entrytool.sortablelist에서 clear할 경우 오류로 인한 수정.

---

src/playground/blocks/hardware/block_joystick.js

block_joystick.js 업데이트

---

src/class/container.js
src/class/painter.js
src/class/playground.js

[#9917](https://oss.navercorp.com/entry/Entry/issues/9917) 처리

이슈 9917 처리

---

src/css/components/container.less

[#9686](https://oss.navercorp.com/entry/Entry/issues/9686) 이슈처리

이슈 9686 처리

---

src/playground/blocks/hardware/block_joystick.js

블록 이름 수정(arduino_get_digital_toggle -> joystick_get_led_number)

Update block_joystick.js 

---

src/playground/blocks/hardware/block_joystick.js

- 조이스틱센서쉴드 블록 방향(대각선)옵션 추가
- 조이스틱 버튼(D10)추가

 Update block_joystick.js

---

src/graphicEngine/FakePIXI.js

[WebGL] FakePIXI - Proxy 객체 사용 제거

---

src/class/entity.js
src/class/pixi/helper/PIXIHelper.ts

[WebGL] 글상자 - 글자색, 배경색 오류 해결

---

src/class/playground.js
src/playground/block.js

- 1.  entrylms quiz에서 clearProject 실행시 painter가 없다고 나옴.
- 2.  체크스크립트 "똑같이 실행되었는가" 블럭 동작중 동일한지 확인하는 부분에서 entry-js로 변경되면서 null로 오던 것이 undefined로 와서 맞춰 줌.

[#9444]   entrylms 방어로직 추가

---

src/class/entity.js
src/class/pixi/atlas/EntryTextureOption.ts
src/class/pixi/utils/logs.ts

[WebGL] 글상자 테두리 제거 ( #10022 ) 
console.log 제거

[WebGL] 글상자 테두리 제거 ( #10022 )

---

src/playground/workspace.js

블록 실행중일때, 선택된 블록이 DELETE로 삭제되지 않도록 수정
1. workspace.js
- Entry.engine.isState('run') 체크 항목 추가 
.

Issue/9923 블록 실행시 DELETE 키 삭제 기능 제거

---

src/playground/block_view.js

issue https://oss.navercorp.com/entry/Entry/issues/9797

adjust baseline alignment

---

src/playground/field/field.js

https://oss.navercorp.com/entry/Entry/issues/9934

이슈 9934 처리

---

src/class/engine.js

1. engin.js 
- Entry.type="minimize" 인경우 소스코드가 중복으로 등들어가 있던 부분 삭제..

Issue/9998 엔진좌표 중복 코드 제거

---

src/playground/workspace.js
src/textcoding/parser.js
src/textcoding/parser/core/text/pyToBlock.js

- parse 내부 코드에서 단순 error 만 throw 하는데 받는 catch 에서
error.line 등과 같은 존재하지 않는 변수를 찾아서 에러발생
- line 을 반환하도록 수정과 동시에 없는 경우 분기처리
- 에러 발생시 workspace 의 타입을 정상적으로 수정

[issue/9243] 정의되지 않은 함수를 작성했을 때 오류 토스트가 발생하지 않음

---

src/playground/field/keyboardInput.js

[#9948](https://oss.navercorp.com/entry/Entry/issues/9948)
이슈 처리

9948 이슈 마무리

---

src/textcoding/parser/core/block/blockToPy.js
src/textcoding/parser/core/text/pyToBlock.js

- 인자값이 숫자가 아닌경우 "" 추가 및 블록으로 변환시 체크로직 수정

[issue/10061] is_press_some_key 의 인자값 버그 수정

---

extern/lang/code.js
extern/lang/ebs.js
extern/lang/en.js
extern/lang/jp.js
extern/lang/ko.js
extern/lang/vn.js
src/playground/block_entry.js
src/playground/blocks/index.js

- 기존 Lang 파일의 type 은 fallbackType 을 말하는 값을 가졌기 때문에 ko, en 말고는 사용되지 않았습니다. 그런데 특정 위치에서는 해당 값을 실제 언어타입으로 적용한 코드들이 있어서 제2외국어 모드에서 강제로 영어로 동작했습니다.  
이와 같은 부분을 해결하고자 type, fallbackType 으로 프로퍼티를 나눴습니다.
- Entry workspace 에서 refresh 없이 블록만 리로드 하는 경우, 하드웨어 블록이 중복으로 EntryStatic 에 추가되던 문제 수정

[Issue/10056] 하드웨어 블록 번역이 정상적이지 않음

---

extern/util/static.js
extern/util/static_mini.js
src/class/playground.js

https://oss.navercorp.com/entry/Entry/issues/10138

[#10138] 글상자 폰트 추가.

---

src/playground/blocks/block_judgement.js

[#10157](https://oss.navercorp.com/entry/Entry/issues/10157) 이슈처리

10157 이슈처리

---

src/class/project.js
src/log/state_manager.js
src/util/utils.js

[#9952](https://oss.navercorp.com/entry/Entry/issues/9952) 이슈처리

이슈 9952 처리

---

src/entry.js
src/playground/block_entry.js
src/playground/block_entry_mini.js

- 기존 : 최초 Entry 생성시 Entry.block 에 교과형블록을 assign.
블록을 리로드한 경우 교과형 블록 증발
- 수정 : 블록을 리로드할때마다 모드 체크 후 assign

[CS]교과형 블록 로딩 로직 개선

---

src/class/playground.js
src/playground/globalSvg.js

3.25.0 Release

---

src/playground/blocks/hardware/block_chocopi.js

LED,모터,서보등을 작동시키는 오프라인 파일을 불러오면 오류나는 문제 해결.

fix offline file open block failure

---

src/class/variable_container.js
src/playground/workspace.js
src/textcoding/error/textCodingError.js
src/textcoding/parser/core/block/blockToPy.js
src/textcoding/util/textCodingUtil.js

등록된 함수에 관하여
- 숫자로 시작하는 경우
- 예약어가 사용된 경우
- 특수문자가 포함된 경우
변환금지처리.
추가로
- 함수명이 없는 경우, '함수' 로 자동지정
- 예약어에 None 추가

[Issue/10160] 엔트리파이선 모드변환시 함수 체크로직 추가

---

webpack_config/common.js

entry-tool 분리
@chanlee 
@leunge 
@prisml

add externals

---

src/playground/block_entry.js
src/playground/field/textInput.js

https://docs.google.com/spreadsheets/d/1yZ9K5Eu03iQhApXgCVCNvpLVk-Z4opjEPxNMXDIkzUs/edit#gid=0

[#10178] 더미 블럭 글씨 크기로 인한 타입 변경.

---

src/playground/workspace.js

[#10256] Entry.Workspace.MODE_OVERLAYBOARD 일 경우가 없어 isBlockCodeView false가 되어 함수일 경우 붙여넣기 안되었음. 추가함.

[#10256] 단축키 붙여넣기 이슈 처리.

---

src/class/playground.js
src/playground/toast.js

new Toast 시, 인자로 입력받은 보드에 토스트 템플릿 엘리먼트가 없으면 재생성하도록 조건 추가

[issue/10203] 토스트 기존 인스턴스 반환 조건 추가

---

src/playground/blocks/block_judgement.js

[#10245](https://oss.navercorp.com/entry/Entry/issues/10245) 이슈처리

=== 비교 로직 변경

---

src/playground/globalSvg.js

[#10367](https://oss.navercorp.com/entry/Entry/issues/10367)
기존 blockMenuWrapper
변경 blockMenuContainer

블록 삭제영역 변경

---

src/textcoding/parser.js
src/textcoding/parser/core/block/blockToPy.js
src/textcoding/parser/core/text/pyToBlock.js

[#10245](https://oss.navercorp.com/entry/Entry/issues/10245)
엔트리 파이선 모드에서 실행 또는 변환시 숫자, 문자처리 방식을 좀더 세분화

파이선 변환과정에서 숫자 처리 세분화

---

src/playground/block_entry.js

Entry.reloadBlock 시 블록목록 중 상속이 있는 경우에도 대응할 수 있도록 수정

[feature] reload 시 상속관계가 있는 블록 스키마도 재상속하도록 추가

---

src/textcoding/parser.js

[#10214](https://oss.navercorp.com/entry/Entry/issues/10214) 이슈 처리
실제 적용은 https://github.com/entrylabs/entryjs/tree/deploy/snapshot_20190523 
브랜치에 적용되는것이나,
이쪽에도 같은 처리를 하였습니다.

parser 라인예외 처리

---

src/util/utils.js

[#10420](https://oss.navercorp.com/entry/Entry/issues/10420) 이슈 처리
블록 사용에도 함수, 변수, 리스트, 신호 정보 추가.

이슈 10420 처리

---

src/class/variable_container.js

[#10429](https://oss.navercorp.com/entry/Entry/issues/10429)
신호의 경우 name키를 다르게 적용해야 하는데 이와 같은 구현이 빠져있었음.

이슈 10429 처리

---

src/class/variable_container.js

[#10427](https://oss.navercorp.com/entry/Entry/issues/10427) 처리
변수 생성 시점 조절
1. 기존
1. 변수 스테이지에 그리고 이름 세팅
1. 변경
1. 변수 이름 변경후 스테이지에 그림

이슈 10427 처리

---

src/playground/block_view.js

@chanlee 이미지에 scale NaN이 발생할수 있는 케이스 처리

hotfix processSvg scale처리

---

src/playground/blocks/hardware/block_mindpiggy.js

블록이 연속될경우 마지막 블록만 적용되던 문제 해결. 최소 딜레이값 15~20ms.

neo블록 딜레이 추가

---

src/playground/blocks/block_expansion_tts.js

읽어주기 확장블록 http 주소가 잘못될 경우 다음 실행부터 소리가 나오지 않음. 방어코드 추가.

[#10154] 읽어주기 확장블록 방어코드 추가.

---

src/class/hw.js

이벤트 등록되어 있을경우 lms 팝업. 없을경우 기존대로 가도록 작성

lms hardware popup 추가.

---

src/class/object.js

[#10479](https://oss.navercorp.com/entry/Entry/issues/10479) 이슈 처리
해당 이슈는 오프라인 6월 배포에 당장 필요한 부분이기 때문에, deploy/offline_v2.0.8 브랜치에 선 병합하겠습니다.  
(web 에는 영향 없음)

[issue/10479] backpackDisabled 시 오브젝트 컨텍스트에도 해당메뉴 미표기

---

src/class/playground.js
src/textcoding/util/textCodingUtil.js

[#10424](https://oss.navercorp.com/entry/Entry/issues/10424) 처리

이슈 10424 처리

---

src/playground/blocks/hardware/block_turtle.js

- feature/module 브랜치에 적용되어있던 block_turtle.js 코드 복사본입니다.
---
- lint 적용
- setLanguage 없이 과거 다국어 방식을 사용하던 부분 전체삭제
- roboid_* 로 연결되어있던 프로퍼티를 전부 turtle_* 로 변경

[feature] turtle 하드웨어 다국어지원 방식 변경 및 일본어 추가

---

src/playground/blocks/hardware/block_davinci.js

브랜치 수정해서 PR 보내드립니다.
- 블럭 색상 수정
- davinci p2 지원 추가

Davinci AI 블럭 색상 수정본

---

.eslintrc
example/example.ejs
example/example_mini.ejs
example/example_webgl.ejs
src/class/hw.js
src/class/playground.js
src/playground/block_menu.js
src/util/utils.js

- Entry.initOptions 플래그 추가시 카테고리를 없애는 로직입니다.
- disableHardware: true 시, 카테고리에서 제외(데이터 자체를 BlockMenu에서 제외)

[Issue/10483] disableHardware 플래그 추가

---

src/class/container.js

[#10467](https://oss.navercorp.com/entry/Entry/issues/10467) 처리
오브젝트 select마다 좌표 업데이트 처리

이슈 10467 처리

---

src/playground/blocks/hardware/block_thinkboard.js

Servo motor 360 text change

---

src/playground/blocks/block_expansion_translate.js

https://oss.navercorp.com/entryline/web/issues/217

[#217] 파파고 번역 블록 옵션 설정된 언어에 따라 순서 변경.

---

src/class/variable_container.js

속성 > 리스트 > 리스트 추가하기
1.  신규 작품 리스트 입력 카운트 최대 5000건으로 제한하도록 변경
2. 기존 작품 로드 입력 리스트 카운트까지만 노출되도록 수정
Entry oss : https://oss.navercorp.com/entry/Entry/issues/10003#event-11348454

Issue/10003 리스트 항목수 입력 제한

---

src/class/object.js

[#10486](https://oss.navercorp.com/entry/Entry/issues/10486)

#10486 작품 실행중 오브젝트 삭제 금지

---

extern/util/static.js
src/class/engine.js
src/class/entity.js
src/class/playground.js
src/playground/block_entry.js
src/playground/block_view.js
src/playground/blocks/block_calc.js
src/playground/blocks/block_expansion_tts.js
src/playground/blocks/block_sound.js
src/playground/trashcan.js
src/util/utils.js

[#10555] 소리 크기 각각 사용하도록 수정, 읽어주고 기다리기 블록 생성.

---

src/class/container.js

[#10558](https://oss.navercorp.com/entry/Entry/issues/10558)

[#10558] 좌표 설정 관련 이슈

---

src/playground/blocks/hardware/block_mechatronics_4d.js

block_mechatronics_4d.js 파일 수정

---

src/class/object.js
src/playground/block_menu.js
src/playground/block_menu_scroll.js
src/playground/zoom_controller.js

[#155] backpack 이동시 textbox 이미지 설정
[#66] workspace 스크롤 바 색상 변경, 오브젝트 사이 라인 컬러수정 및 사이즈 수정.
[#66] zoom icon 변경.

entryline 이슈 처리.

---

src/class/playground.js

https://oss.navercorp.com/entryline/lineentry/issues/137

[#137] 나의 보관함 alt 태그 변경 ( 코멘트 보여주기 -> 나의 보관함 )

---

src/playground/thread.js

[#10701](https://oss.navercorp.com/entry/Entry/issues/10701) 처리

이슈 10701 처리

---

src/css/components/playground.less

[#10734](https://oss.navercorp.com/entry/Entry/issues/10734) 처리

이슈 10734 처리

---

src/class/object.js

https://oss.navercorp.com/entry/Entry/issues/10641

[#10641]  처리.

---

src/class/Expansion.js

[#10756](https://oss.navercorp.com/entry/Entry/issues/10756) 처리

이슈 10756 처리

---

src/class/variable_container.js

https://oss.navercorp.com/entryline/lineentry/issues/245

[#line/245] remove function error 수정.

---

src/class/variable_container.js

- 해당 버튼으로 속성 탭으로 이동 후, 변수/리스트 추가 버튼 클릭시
최초 클릭에서 아무런 반응이 없고, 두번째 클릭 때 오픈됨
- 최초 클릭때 상태는 close 이나 isOpen 속성만 true 가 되어서
첫 클릭시 open 동작이 아닌 close 동작이 실행

[#issue/line/287] 변수블록 카테고리 내 변수/리스트 추가버튼 로직 수정

---

package-lock.json
src/playground/blocks/hardware/block_blacksmith.js

1. PIR센서 추가 블록을 만들었습니다.
2. 블루투스 TX값 함수명이 잘못 설정되어 있어 블록이 나타나지 않아 수정 하였습니다.

[대장장이보드] PIR센서 블록 추가와 블루투스 TX값 함수 수정

---

src/css/components/variable_container.less
src/util/utils.js

[#10788](https://oss.navercorp.com/entry/Entry/issues/10788)처리
추가적으로 처음로드 할때 함수가 리스트에 표기되지않는 문제도 같이 처리하였습니다.

이슈 10788 처리

---

src/playground/blocks/block_expansion_tts.js
src/util/utils.js

https://oss.navercorp.com/entry/Entry/issues/10747

[#10747] 실행중인 instance의 볼륨 수정하도록 변경.

---

src/playground/blocks/hardware/block_asomebot.js

* udp 메시지 수신하면 삭제하도록 (중복 적용 안되도록)
* 중심잡기 블록 오류 수정
* 부저 주파수로 소리내기 오류 수정
* 발목 비틀기 동작 오류 수정
* 걷기 속도 조절 블록 추가

어썸봇 오류 수정 및 기능 개선

---

src/playground/blocks/hardware/block_asomebot.js

* 부저를 {0} 주파수로 {1}초 연주하기 블록에서 실행이 멈추는 오류 수정
* 발목 비틀어서 발바닥 들기 블록의 파이선 코드 오류 수정
* 어썸봇 중심잡기 오류 수정 / 핀의 초기화에서 부저와 모터 이외 다른 핀은 제외 시킴
* 수신된 udp 메시지를 구별할 수 있도록 id 추가, 중복해서 메시지를 처리하고 싶지 않을 때 사용
* 걷기 속도 조절 블록 추가
* 파이썬 코드의 오타 수정

[develop-hw to develop] 어썸봇 오류 수정 및 기능 개선 (#1445)

---

src/class/container.js

[#10771](https://oss.navercorp.com/entry/Entry/issues/10771)

이슈 10771 처리

---

src/playground/field/textInput.js

https://oss.navercorp.com/entryline/lineentry/issues/364

[#364] append blur event.

---

src/class/painter.js

https://oss.navercorp.com/entry/Entry/issues/10951

새그림 생성 시, 다른 모양의 이미지가 노출 되는 현상

---

src/playground/blocks/hardware/block_asomebot.js

ESP8266 보드 내부에 설치된 LED가 GPIO에 음극이 연결되어 반대로 동작하는 것을 소스에 적용함

built-in LED가 반대로 동작하는 것에 맞춰서 소스 수정

---

src/playground/blocks/hardware/block_mechatro.js

[issue/10972] 메카트로나노의 이미지, 타이틀 수정 + 린트적용

---

src/css/components/playground.less

https://oss.navercorp.com/entry/Entry/issues/10995

issue 19885 hotfix

---

src/class/variable_container.js

line issue : https://oss.navercorp.com/entryline/lineentry/issues/441

[#line/441] variable container clear시 삭제 되지 않는 부분 처리.

---

src/class/container.js

[#10906](https://oss.navercorp.com/entry/Entry/issues/10906) 처리

이슈 10906 처리

---

README.md

제가 아는대로 수정했는데 부족한 부분은 확인 부탁드립니다.

[feature/modify_readme] README.md 수정

---

extern/util/handle.js
src/class/pixi/handle/PIXIHandle.js
src/graphicEngine/GEHandle.js

@chanlee [#11023](https://oss.navercorp.com/entry/Entry/pull/11023) 수정하면서 발견한 IE오류도 같이 수정합니다.

ie에서 발생하는 문법오류 수정

---

src/class/scene.js

엔트리/엔트리라인
신규 장면 생성후 모든 장면을 모두 삭제시도, Undo시 장면까지 복제되는 부분수정

[#432] scene이 1개일 때 삭제 시도 후 실행취소 시 에러 발생. 로그 쌓지 않도록 수정.

---

src/css/components/playground.less

Reverts entrylabs/entryjs#1521

Revert "[issue/line #311]"

---

src/class/container.js

@chanlee [#10569](https://oss.navercorp.com/entry/Entry/issues/10569) 이슈에 대해서 방어 로직 추가하였습니다.

add object null check

---

src/class/container.js
src/class/playground.js
src/css/components/playground.less

https://oss.navercorp.com/entry/Entry/issues/10836

add dimmed when no object

---

src/class/function.js
src/class/object.js
src/class/scene.js
src/class/variable_container.js
src/command/commands/block.js
src/command/commands/function.js
src/playground/block.js
src/playground/block_entry.js
src/playground/blocks/block_func.js
src/playground/board.js
src/playground/code.js
src/util/static.js

https://oss.navercorp.com/entryline/lineentry/issues/389

함수 히스토리 기능 오류 수정. 

---

src/class/hw.ts

- 클라우드PC 진입은 close -> reconnect 순임
재연결로직 문제가 있어 연결시도를 안하던 문제 수정
- 하드웨어 프로그램 연결 -> 종료 시 최초 블록모양으로 바뀌지 않는 점 수정
소켓 완전히 신규 객체로 받지 않고 기존 소켓을 재활용 하다보니,
reconnect 이벤트가 아니었기때문에 플래그에 영향을 주지 않았음

[hotfix/11139] 하드웨어 소켓 종료 후 대응 수정 

---

src/class/variable_container.js

[Entry#11167](https://oss.navercorp.com/entry/Entry/issues/11167) 이슈처리

이슈 11167 처리

---

src/class/hw.ts

워크스페이스 사파리 하드웨어 연결  링크 수정
1. 크롬링크와 같이 사용하던 부분 분리
2. 사파리 브라우저에서 iframe 요청시 페이지가 전환되는 부분 수정

워크스페이스 > 하드웨어 연결 블록 오류 수정

---

src/playground/blocks/hardware/block_blacksmith.js

'블루투스 블록' 명세 변경
- 파라미터 삭제
'블루투스 블록' 로직 변경
- 숫자/문자 구분 로직 삭제, 수신값 그대로 출력.

[대장장이보드] 블루투스 기능 수정

---

src/playground/blocks/hardware/block_pingpong.js

- 도트 메트릭스 블럭 출력 관련 수정사항 적용
- send command 관련 코드 정리

[PINGPONG] 도트 메트릭스 블럭 수정

---

src/playground/blocks/hardware/block_neobot_game_theme.js

Fixed wrong variable names of neobot_judge_coord block

---

src/class/entity.js

https://oss.navercorp.com/entry/Entry/issues/11278
1. 둥근모꼴체 변경시 fontSize로 lineHeight 값이 변경되도록 추가

Issue/11278 둥근모꼴체 lineHeight 변경추가

---

package-lock.json
package.json
webpack_config/prod.js
yarn.lock

https://github.com/entrylabs/entryjs/pull/1557 에서 파생된 PR 입니다.
https://github.com/webpack-contrib/uglifyjs-webpack-plugin
uglifyjs 가 deprecated 되어서, terser webpack plugin 으로 수정하였습니다.
production 적용건이므로 한번 확인 부탁드려요

[feature] uglifyjs to terser

---

src/class/object.js
src/class/playground.js
src/class/scene.js
src/command/commands/container.js
src/command/commands/playground.js
src/util/utils.js

https://oss.navercorp.com/entry/Entry/issues/11202

[issue/11202] 장면,오브젝트 소리 삭제시 소리 정지

---

src/class/engine.js
src/util/init.js

- url체크하지 않음 -> url리스트 사이즈 확인 하는 방향으로 변경
- 함수로 빼기.

sound 가 없는경우 실행되지 않는 문제

---

src/playground/blocks/block_ai_utilize_audio.js
src/playground/blocks/block_ai_utilize_translate.js
src/playground/blocks/block_ai_utilize_tts.js
src/util/audioUtils.js

https://github.com/entrylabs/entry-tool/pull/123

sponser Text 추가

---

src/playground/blocks/block_ai_utilize_audio.js
src/util/audioUtils.js

https://oss.navercorp.com/entry/Entry/pull/11323

[issue/audio_block] 블록 상세 관련 수정

---

src/class/AIUtilize.js
src/util/audioUtils.js
src/util/utils.js

[#11326](https://oss.navercorp.com/entry/Entry/issues/11326)

[오디오 블록] 마이크 연결 되지 않은 케이스, 활성화 에러 수정

---

src/extensions/CloudVariable.js

[#11332] disconnect시에 온라인으로 바뀌도록 설정.

---

images/beta_tag.svg
src/css/components/block_menu.less
src/playground/block_menu.js

https://oss.navercorp.com/entry/Entry/issues/10910#issuecomment-3992874

AI블록, 데이터분석 블록메뉴 betaTag 추가

---

src/command/commands/variableContainer.js
src/extensions/CloudVariable.js

이슈 11332 처리

---

src/command/commands/variableContainer.js
src/extensions/CloudVariable.js

이슈 11332 처리 (#1615)

---

src/util/audioSocket.js
src/util/audioUtils.js

https://oss.navercorp.com/entry/Entry/pull/11378

[오디오블록] 서버 경로 변경 

---

src/util/audioUtils.js

https://oss.navercorp.com/entry/Entry/pull/11385

[오디오 블록] Firefox disable

---

src/playground/blocks/block_variable.js

[#11400](https://oss.navercorp.com/entry/Entry/issues/11400)

이슈 11400 처리

---

src/util/audioUtils.js

[#11403](https://oss.navercorp.com/entry/Entry/pull/11403)

[오디오 블록] 샘플링 레이트 변경 방법 수정

---

extern/util/static.js
yarn.lock

https://oss.navercorp.com/entry/Entry/issues/11428

[static] 블럭메뉴 순서 변경

---

src/class/DataTable.js
src/class/playground.js

https://oss.navercorp.com/entry/Entry/issues/11433

[DataTable] 테이블 편집 이벤트 처리

---

src/class/playground.js

https://oss.navercorp.com/entry/Entry/issues/11466

[playground] 탭이동시 테이블 수정 모달 호출

---

src/class/DataTable.js

- tempDataAnalytics 삭제 위치 수정
- 원래위치에서는 setData하면서 삭제해도 다시 생성됨
https://oss.navercorp.com/entry/Entry/issues/11474

[DataTable] 테이블 수정이벤트

---

src/class/playground.js

https://oss.navercorp.com/entry/Entry/issues/11474#issuecomment-4074400

[playground] 탭 이동시 수정 취소하면 원래 값으로 초기화

---

src/playground/blocks/block_ai_utilize_audio.js
src/playground/scope.js
src/util/audioUtils.js

[#11477](https://oss.navercorp.com/entry/Entry/issues/11477)

[issue/11477] 오디오 블록 오류 메세지 뜨는것 수정

---

src/playground/blocks/hardware/block_pingpong.js
src/playground/blocks/hardware/block_pingpong_multi.js

도트 지우기 블럭 동작 시 HW에서 처리 지연시간 필요하여 블럭 대기시간 추가

 pingpong: 도트지우기 블럭 실행 후 대기시간 추가

---

src/class/playground.js
src/class/source/DataTableSource.js

[issue/11564] 저장 전 테이블 수정 확인.

---

package.json
yarn.lock

라인에서 로드가 안되는 이슈와 관련되서 babeling 에서 필요한 core-js 를 추가하였습니다. 
[#817](https://oss.navercorp.com/entryline/web/pull/817)

core-js 추가

---

src/class/DataTable.js

https://oss.navercorp.com/entry/Entry/issues/11566
- 변경사항 체크를 위해 만들어둔  temp 변수 활용

[DataTable] 테이블 행 추가 후 저장 시, 추가한 행이 초기화 됩니다

---

src/class/playground.js
src/class/source/DataTableSource.js

https://oss.navercorp.com/entry/Entry/issues/11569
- command로 dataTableAddSource 할때 두번 selectTable을 함
- 두번 selectTable을 하면서 원래 tab을 잃어버림

[playground] 빈 테이블 추가시 탭이 선택되지 않음

---

src/class/engine.js
src/css/components/engine.less
src/util/videoUtils.ts

[#11578](https://oss.navercorp.com/entry/Entry/pull/11578)
https://github.com/entrylabs/entry-tool/pull/162

[로딩 팝업] 비디오 블록 로딩 화면 변경

---

src/extensions/CloudVariable.js

[#10759](https://oss.navercorp.com/entry/Entry/issues/10759)

add imAlive

---

src/playground/blocks/hardware/block_thinkboard.js

apply W/A get Servo Motor 180 angle for Thinkboard

apply W/A for servo angle value reading

---

src/class/playground.js

[#11598](https://oss.navercorp.com/entry/Entry/issues/11598)

이슈 11598처리

---

extern/util/static.js
src/playground/blocks/block_ai_utilize_video.js

[#11614](https://oss.navercorp.com/entry/Entry/pull/11614)

비디오 블럭 QA 수정

---

src/graphicEngine/GEHelper.ts
src/util/videoUtils.ts

[#11621](https://oss.navercorp.com/entry/Entry/issues/11621)

이슈 11621 처리

---

src/util/utils.js

add cloudVariable json.parse

---

src/playground/blocks/block_calc.js
src/playground/scope.js
src/util/utils.js

[#11589](https://oss.navercorp.com/entry/Entry/issues/11589)

[#11589] getNumberValue, calc_basic 블록 수정

---

src/playground/blocks/block_ai_utilize_video.js
src/util/videoUtils.ts

https://oss.navercorp.com/entry/Entry/issues/11398#issuecomment-4225493
entry-tool: https://github.com/entrylabs/entry-tool/pull/171
Entry: https://oss.navercorp.com/entry/Entry/pull/11622

비디오 블록 로딩 화면 문구 수정

---

src/playground/blocks/block_calc.js
src/util/utils.js

[#11589](https://oss.navercorp.com/entry/Entry/issues/11589)
isNaN때문에 생긴 block_menu _convertSelector에서 생기는 에러

#11589 오류 수정

---

src/class/entity.js
src/class/pixi/etc/PIXIBrushAdaptor.ts

[#11626](https://oss.navercorp.com/entry/Entry/issues/11626)
관련 이슈 : [#11434](https://oss.navercorp.com/entry/Entry/issues/11434)

이슈 11626처리, eraseBrush webGL분기 추가

---

src/playground/blocks/block_ai_utilize_video.js
src/util/videoUtils.ts
src/util/workers/video.worker.ts

비디오 블럭 로딩 개선입니다. 기존의 로딩이 너무 길던 부분에 대해서 수정할수 있는 부분에 대해서 최대한 수정하였습니다.

[WIP]비디오 블럭 로딩 개선

---

src/extensions/dmet.js

issue https://oss.navercorp.com/entry/Entry/issues/10569#issuecomment-4282129

hotfix for slide type variable

---

src/playground/blocks/block_ai_utilize_video.js
src/util/videoUtils.ts
src/util/workers/motion.worker.ts
src/util/workers/video.worker.ts

모델 사용에 대해서 최적화를 하였습니다.
현재 로딩창과 관련하여서 커뮤니케이션 중입니다.

[비디오 블럭] 추가 개선

---

src/playground/blocks/hardware/block_orange.js

#1729 
수정 반영하였습니다.
오렌지보드 ID 1.E로 수정
드롭다운 블록 색상 수정

orange.js 추가

---

src/class/variable_container.js

[#11653](https://oss.navercorp.com/entry/Entry/issues/11653) 처리

이슈 11653 처리

---

src/class/variable/variable.js
src/util/binPacking.js

[#11644](https://oss.navercorp.com/entry/Entry/issues/11644)

add binPacking

---

extern/util/static.js
src/entry.js
src/playground/blocks/block_ai_utilize_video.js
src/playground/field/dropdownExtra.js
src/playground/field/field.js

[#11691](https://oss.navercorp.com/entry/Entry/issues/11691)

[WIP][#11691] 비디오 블럭 사물 판단 블록

---

src/playground/blocks/block_ai_utilize_video.js

https://oss.navercorp.com/entry/Entry/issues/11691

[#11691] 다국어 설정 관련 수정

---

src/class/toast.js
src/graphicEngine/GEHelper.ts
src/playground/blocks/block_ai_utilize_video.js
src/util/videoUtils.ts
src/util/workers/video.worker.ts

https://oss.navercorp.com/entry/Entry/issues/11683

[비디오 블럭] 로딩 수정 및 호환성 개선

---

src/class/pixi/plugins/PIXITextMetricsPlugIn.js
src/class/variable/variable.js
src/playground/blocks/block_brush.js

[#11688](https://oss.navercorp.com/entry/Entry/issues/11688)

[#11688] 모든붓 지우기 관련 이슈

---

src/class/scene.js
src/css/components/scene.less

https://oss.navercorp.com/entry/entry/issues/11521
1. 기본 작성가능한 장면갯수 수정
2. 장면 체크 로직수정
3. 브라우저 사이즈 기준으로 이전, 다음 장면전환 버튼이 노출되도록 변경

Issue/11521 워크스페이스 장면30개로 변경

---

src/class/scene.js

https://oss.navercorp.com/entry/Entry/issues/11707
1.작품상세페이지에서 장면리스트의 offsetWidth 불러오지 않도록 수정

Issue/11707 offsetWidth 설정조건추가

---

src/util/videoUtils.ts

[#11642](https://oss.navercorp.com/entry/Entry/issues/11642?email_source=notifications&email_token=AAADGFWKL6L6Z7JEQKIR6DDROTQD5A5CNFSM4ABECRQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOABBF2YQ#issuecomment-4349282)

[비디오블럭] 에러 토스트 수정

---

src/graphicEngine/GEHelper.ts
src/util/videoUtils.ts

[11683](https://oss.navercorp.com/entry/Entry/issues/11683)

[#11683]파이어폭스 비디오 비율 개선

---

src/graphicEngine/GEHelper.ts

[#11683](https://oss.navercorp.com/entry/Entry/issues/11683?email_source=notifications&email_token=AAAAQRQZSXJK4OWUXNSIL6LRO6MMJA5CNFSM4ABEVCC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOABBIP4Y)

[#11683] 비디오블럭 파폭/부스트모드 카메라 비율 재조절

---

src/util/videoUtils.ts

[#11709](https://oss.navercorp.com/entry/Entry/issues/11709)

#11709 처리, 오브젝트 범위 확인 후 재설정

---

src/textcoding/parser.js

[#11753](https://oss.navercorp.com/entry/Entry/issues/11753)

#11753 엔트리 파이썬 parser 방어 로직 추가

---

src/playground/blocks/hardware/block_mechatro.js

[Mechatro 하드웨어] mapping 블록 수정

---

extern/util/static_mini.js
src/playground/block_entry_mini.js
src/playground/blocks/hardware/block_robotisDream.js

add dream block

---

src/playground/blocks/hardware/block_abilix_Krypton0.js

Ablix krypton 버그 수정
- Sound 관련 오류 수정
- LED 관련 오류 수정
ESLINT 관련 수정

Abilix Krypton 버그 수정 및 eslint 적용

---

src/playground/block_menu.js

[#11856](https://oss.navercorp.com/entry/Entry/issues/11856)
연관 PR
https://github.com/entrylabs/entryjs/pull/1815

#11856 수정, 연관이슈 11841

---

src/entry.js
src/util/functions/showConsoleBanner.ts

- 위 같은 콘솔배너를 추가해줍니다
- 그냥 저희도 하나 있으면 재밌지 않을까 해서 넣어봤습니다
- 엔트리 친구들 중 개발자 콘솔을 드나드는 친구들이 있는거 같아서 이참에 만들어봤습니다
- 디자인은.. 그냥 맘에드는걸로 해봤습니다!
- 색상은 엔트리 공식 색상값을 가져왔습니다

[chore] 개발자 콘솔에 엔트리 배너 추가

---

src/class/engine.js
src/playground/block_menu.js
src/playground/field/keyboardInput.js
src/textcoding/static/keyboardCode.js
src/util/utils.js

[#11841](https://oss.navercorp.com/entry/Entry/issues/11841)

#11841 IE화살표 이슈 수정

---

src/class/stage.js
src/playground/block_menu.js
src/playground/block_menu_scroll.js
src/playground/block_view.js
src/playground/board.js
src/playground/globalSvg.js
src/playground/scroll.js

[#11075](https://oss.navercorp.com/entry/Entry/issues/11075)
해당 부분이 revert 된것으로 보입니다.... 다시 추가하여 PR 올립니다!

[#11075] 에러 수정

---

src/textcoding/parser/core/block/blockToPy.js

[#7994](https://oss.navercorp.com/entry/Entry/issues/7994)

[#7994] 소괄호 생성 규칙 변경

---

src/class/container.js

[Line#563] 프린트 오류 수정

---

src/playground/blocks/hardware/block_LineCoding.js
src/playground/blocks/hardware/block_ssboard_nano.js

스피커출력 시간조절

---

src/playground/blocks/hardware/block_orange.js

오렌지보드 업데이트

---

src/playground/blocks/hardware/block_LineCoding.js

- 부저 ON OFF TIME 시간 서로 바뀌어 있음 - 수정
- 서보블록 실시간제어와 저장제어 내부 번호 수정 
- bmotor 속도 음수적용
- line 직진시간 음수적용
- 디지털 포트 저장모드에서 저장메모리 데이터 변환 수정
-  ffmotor, bbmotor, motorstop - 통신모드동작 패킷발신 수정

부저, bmotor등 수정

---

src/playground/blocks/block_calc.js

[#12014](https://oss.navercorp.com/entry/Entry/issues/12014)

[#12014] 특정 작품 관련 오류 수정

---

src/playground/blocks/hardware/block_mechatro.js

1. 클래스 형식으로 변경
클래스 구조로 바꾸어 변경량이 많아보입니다.
실제로는 아래 나열한 부분만 변경 되었습니다.
2. 이벤트 블록 추가
- afterReceive() 추가
- 이벤트 블록 추가: mechatro_event_rising, mechatro_event_falling
3. 송신 자료 구조 변경에 따른 함수 수정
SetZero()
transferModeValue(), transferValue(), transferMode()

이벤트 블록 추가 외

---

src/util/videoUtils.ts

[#12026](https://oss.navercorp.com/entry/Entry/issues/12026)

이슈 12026 처리, 비디오 워커 관련 방어 코드 추가

---

src/util/videoUtils.ts

[#12029](https://oss.navercorp.com/entry/Entry/issues/12029)

#12029 방어 로직 추가

---

.eslintrc
package-lock.json
package.json
src/class/playground.js
src/util/utils.js

[#278](https://oss.navercorp.com/entry/entry2/pull/278)

오브젝트 관련 작업 처리

---

src/playground/blocks/hardware/block_hasseam.js

- D/A수신블록에 기본or풀업 선택할수있도록 드롭다운추가
※ 하드웨어 테스트 없이 PR부탁드립니다.

하쌤보드 로직 작성, 수신블록 풀업 옵션추가

---

package.json
src/class/entity.js
src/util/utils.js
yarn.lock

[#12089](https://oss.navercorp.com/entry/Entry/issues/12089)
벤치마크상 가장 빠른 방법으로 적용했습니다.
```bash
mathjs chain bignumber x 139,348 ops/sec ±1.47% (87 runs sampled)
mathjs evaluate bignumber x 15,001 ops/sec ±1.33% (87 runs sampled)
mathjs evaluate bignumber2 x 34,684 ops/sec ±0.97% (85 runs sampled)
Fastest is mathjs chain bignumber
```
``` javascript
const Benchmark = require("benchmark");
const { evaluate, chain, create, all, bignumber } = require("mathjs");
const math = create(all, {
number: "BigNumber",
});
var suite = new Benchmark.Suite();
// add tests
suite
.add("mathjs chain bignumber", function () {
const left1 = bignumber(3000);
const left2 = bignumber(-3000);
const right = bignumber(360);
chain(left1).mod(right).add(right).mod(right).value.toNumber(); …
```

mod 처리시 소수점 오류 해결

---

src/playground/blocks/hardware/block_LineCoding.js

LCD제어 글자 수 조정
bwmotor 기본 설정값 수정
wheel블록 연속전송방법 수정
서보모터 초기값 수정

라인코딩 LCD제어등 개선

---

src/util/binPacking.js

[#12125](https://oss.navercorp.com/entry/Entry/issues/12125)

item이 undefinde가 되지 않도록 처리

---

src/util/utils.js

[#12115](https://oss.navercorp.com/entry/Entry/issues/12115)

stopProjectWithToast 처리시 toggleStop 기다리도록 변경

---

src/playground/blocks/hardware/block_exmars_cube.js

eX-Mars hardware block 추가

---

extern/util/static.js
src/class/container.js
src/playground/blocks/block_ai_utilize_video.js
src/util/videoUtils.ts
types/index.d.ts

[#12160](https://oss.navercorp.com/entry/Entry/issues/12160)

비디오 블럭 이슈 관련 수정

---

src/class/DataTable.js
src/util/utils.js

- table 정보가 없을때는 setTables를 하지 않고 setTables안에 addsource를 부를 일이 없음
- setTables말고는 addSource를 부르는 경우는 안보임
https://oss.navercorp.com/entry/Entry/issues/12169

[DataTable] remove initOption

---

src/playground/blocks/hardware/block_byrobot_drone_4.js
src/playground/blocks/hardware/block_byrobot_drone_8.js

1. E-Drone, 코딩 드론 회전 블록에서 시간 지연이 안되는 오류 수정

바이로봇 E-Drone, 코딩 드론 수정

---

extern/util/static.js
src/playground/blocks/block_ai_utilize_video.js
src/playground/field/dropdownDynamic.js

dropdownDynamic부분에 대한 컨펌이 필요합니다.

dropdownDynamic으로 카메라 변경 블록 관련 부분 추가

---

src/playground/blocks/block_ai_utilize_audio.js
src/playground/blocks/block_ai_utilize_video.js
src/playground/blocks/block_flow.js
src/playground/executors.js
src/util/audioUtils.js
src/util/videoUtils.ts
src/util/workers/video.worker.ts

[#12171](https://oss.navercorp.com/entry/Entry/issues/12171)

[#12171] '인식이 되었는가?' 블록과 '될 때까지 기다리기' 블록조합 오류 수정

---

src/playground/blocks/block_ai_utilize_tts.js

[#12183](https://oss.navercorp.com/entry/Entry/issues/12183)

[#12183] 읽어주고 기다리기 블럭 실행 오류 수정

---

src/playground/blocks/block_ai_utilize_tts.js
src/util/utils.js

읽어주고 기다리기를 연속으로 사용하는 경우 오류가 발생하게 되는 이슈가 있었습니다.
해당 부분은 기존코드에서 return script하는 부분의 처리가 이상하게 되어 생기는 이슈로 보이며, 해당 부분을 비동기 블럭 처리 하였습니다.

[#12183]연속 읽어주고 기다리기 관련 오류 수정

---

src/playground/field/dropdown.js

FieldDropdownDynamic 값을 변경할때 reDraw가 동작하도록 수정.

add reDraw option

---

src/playground/blocks/hardware/block_byrobot_base.js
src/playground/blocks/hardware/block_byrobot_controller_3_4.js
src/playground/blocks/hardware/block_byrobot_controller_4.js
src/playground/blocks/hardware/block_byrobot_drone_3_10.js
src/playground/blocks/hardware/block_byrobot_drone_4.js
src/playground/blocks/hardware/block_byrobot_drone_8.js
src/playground/blocks/hardware/block_byrobot_petrone_v2_base.js
src/playground/blocks/hardware/block_byrobot_petrone_v2_controller.js
src/playground/blocks/hardware/block_byrobot_petrone_v2_drive.js
src/playground/blocks/hardware/block_byrobot_petrone_v2_flight.js

1. setLanguage가 monitorTemplate 아래에 위치하는 경우 listports의 name에서 파일 내부에 있는 Lang을 참조하지 못하는 것을 확인하여 배치 순서를 변경하였습니다.

바이로봇 제품군 monitorTemplate 과 setLanguage의 배치 순서 변경

---

src/playground/blocks/hardware/block_exmars_cube.js

exmars-cube : 블록 추가

---

src/playground/blocks/hardware/block_codeino.js
src/playground/blocks/hardware/block_codewiz.js

CODEino url 수정
CodeWiz url, 오동작 수정, 펌웨어 수정에 따른 변경

CODEino url 수정, CodeWiz url, 오동작 수정

---

src/class/pixi/plugins/PIXITextMetricsPlugIn.js

[#1178](https://oss.navercorp.com/entry/entry2/issues/1178)

[#1178] 부스트모드 에러 수정

---

src/playground/blocks/hardware/block_uglybot.js

sound 센서 값을 0~255에서 -128 ~ 127까지로 변경

sound 센서 값 unsigned => signed 변경

---

src/playground/blocks/hardware/block_LineCoding.js
src/playground/blocks/hardware/block_ssboard_nano.js

라인코딩 - wheel블록 수정
상상보드 - 스피커 동작시간, 음계 초기값 변경

라인코딩-wheel, 상상보드 - 스피커 블록 수정

---

src/playground/blocks/hardware/block_altino_lite.js

https://github.com/entrylabs/entryjs/issues/1972

알티노 라이트 오류 수정

---

src/playground/blocks/hardware/block_dash.js

대시 2021년 1월 업데이트

---

src/class/engine.js
src/playground/block_view.js
src/util/utils.js

[#2262](https://oss.navercorp.com/entry/entry2/issues/2262)

#2262 키 이벤트 오류 수정

---

src/playground/blocks/hardware/block_iboard.js

iboard 블록 수정

---

src/playground/blocks/hardware/block_neobot_purple.js

신규 추가된 하드웨어 NEW 네오봇, NEW 네오봇 (For Cloud PC) 용 블럭 추가

[네오피아] 신규 하드웨어 용 블럭 추가

---

src/playground/blocks/hardware/block_mechatro.js

하드웨어 모니터 리스트 수정
- 이름 단순화, 모터 전류값 표기, 정보표시용 'inform' 추가
모터 전류값 블록 표시 이름에 단위 추가

Develop hw - 하드웨어 모니터 리스트 수정, 블록 이름 수정

---

src/playground/blocks/hardware/block_diaboard.js

block_diaboard.js로 도움말 추가 및 effect 블록 딜레이 조정

[헬로긱스]도움말 및 effect 블록 딜레이 조정

---

src/class/learning/Cluster.js
src/class/learning/NumberClassification.js
src/class/learning/Regression.js

table 열 비교 필드 변경.

---

src/class/DataTable.js

[#3113_3] 프로젝트에 적용된 모델만 나오도록 수정.

[#3113_3] 프로젝트에 적용된 모델만 나오도록 수정.

---

webpack_config/common.js

[#2348](https://oss.navercorp.com/entry/entry2/issues/2348)

exclude 제거

---

src/playground/field/output.js

함수 fieldOutput 블록 하이라이팅 오류 수정
[#3080](https://oss.navercorp.com/entry/entry2/issues/3080)

이슈 3080 처리

---

src/playground/blocks/hardware/block_neobot_purple.js

[네오피아] 버그 수정

---

src/playground/blocks/block_ai_utilize_tts.js

https://github.com/entrylabs/entryjs/pull/1925

[#12183] 리뷰 관련 수정

---

src/class/variable/listVariable.js

[#3206](https://oss.navercorp.com/entry/entry2/issues/3206)

#3206 공유변수 방어 로직 추가

---

src/playground/block_menu.ts

Fix a issue scrolling whole screen when pressing down-arrow indicator

---

src/class/source/DataTableSource.js
src/util/init.js

Reverts entrylabs/entryjs#2083

Revert "#3255 테이블 날짜 지정 관련 방어 코드 + AI, expansion 기능 제거 옵션 추가"

---

src/playground/blocks/hardware/block_lecoboard.js

#2071
[#3267](https://oss.navercorp.com/entry/entry2/issues/3267)

이슈 3267 처리

---

src/playground/blocks/hardware/block_robotry_robit_stage.js
yarn.lock

로빗무대 하드웨어용 블록코드 신규추가

---

src/util/utils.js

오브젝트 있을시 에러 수정

---

src/playground/blocks/hardware/block_robotisRB.js

[알쥐 회전 변경]

---

src/class/variable/listVariable.js
src/util/init.js

[#3539](https://oss.navercorp.com/entry/entry2/issues/3539)

이슈 3539 처리

---

src/class/engine.js

[#3543](https://oss.navercorp.com/entry/entry2/issues/3543)

이슈 3543 처리

---

src/playground/blocks/hardware/block_gbot.js

Fixed LED matrix on time

---

src/playground/blocks/hardware/block_etboard.js

add etboard neopixel block

---

src/playground/blocks/hardware/block_genirobot.js

지니봇 url, Image 수정

---

src/class/DataTable.js
src/class/LiterallycanvasPainter.js
src/class/object.js
src/class/painter.js
src/class/playground.js
src/class/variable_container.js
src/entry.js
src/playground/workspace.js
src/util/init.js
src/util/modal.js
src/util/utils.js

[#3570](https://oss.navercorp.com/entry/entry2/issues/3570)

entry-lms modal을 entry-modal로 전환

---

src/playground/blocks/hardware/block_wearable.js

fix: Wearable 이 proboconnect 객체를 덮어쓰는 문제 수정

---

src/class/object.js

[#2586](https://oss.navercorp.com/entry/entry2/issues/2586) 처리

이슈 2586 처리

---

src/playground/blocks/block_ai_utilize_audio.js

[#3586](https://oss.navercorp.com/entry/entry2/issues/3586)

#3586 사이드 이펙트 수정

---

src/util/audioSocket.js

[#3861](https://oss.navercorp.com/entry/entry2/issues/3861)

이슈 3861 처리

---

src/util/utils.js

[#4003](https://oss.navercorp.com/entry/entry2/issues/4003)

[#4003] 오브젝트 속성 탭, 회전방식 선택 해제 오류 수정

---

extern/util/CanvasInput.js
src/class/pixi/etc/PIXICanvasInput.js

[#4114](https://oss.navercorp.com/entry/entry2/issues/4114)
- 입력창 클릭 영역 수정
- 화면 스크롤된 상태로 클릭 시 위치 값 계산 오류 수정

묻고 대답 기다리기 블록 입력창 클릭 영역 수정

---

src/playground/blocks/block_ai_utilize_tts.js

[#4143](https://oss.navercorp.com/entry/entry2/issues/4143)

[#4143] 읽어주고 기다리기 블록 오류 발생 시 다음 블록 실행

---

src/playground/blocks/hardware/block_runcoding.js

add neopixel block

---

src/playground/blocks/hardware/block_robotry_robit_stage.js

- 소리감지 값 변화가 좀 더 잘 일어나도록 수정
- entry-hw 변경점 X

[로보트리] 로빗무대 블록 소리감지 값 범위 수정

---

src/playground/blocks/hardware/block_castarter_v2.js

안녕하세요~
2세대 코딩어레이 스타터 신규 등록 요청 드립니다.
신규 : 
block_castarter_v2.js

2세대 코딩어레이 스타터 신규 등록 요청드립니다.

---

src/textcoding/util/textCodingUtil.js

[4329](https://oss.navercorp.com/entry/entry2/issues/4239)

issue/4239 

---

extern/util/CanvasInput.js
src/class/pixi/etc/PIXICanvasInput.js

[#4207](https://oss.navercorp.com/entry/entry2/issues/4207)
1. focus setInterval 처리전 requestAnimationFrame 만큼 대기하기
2. touch action 에서는 offset 속성이 없어 client 속성으로 대체하기

이슈 4207 처리

---

src/class/DataTable.js

[#4289](https://oss.navercorp.com/entry/entry2/issues/4289)

[#4289] 작품에 tables 필드가 없는 경우 로딩 오류 수정

---

src/class/engine.js

[#4295](https://oss.navercorp.com/entry/entry2/issues/4295)
[engine] popup에 mouseup이벤트 복사 추가

[#4295] '오브젝트 클릭을 해제했을 때' 블록이 확대 보기에선 동작하지 않음 

---

src/playground/blocks/hardware/block_codewiz.js

- 부저 > 스피커 명칭변경
- OLED 한글 출력블록 추가
- 도트매트릭스 n번 지우기 오류 수정
- 각 블록 설명부분 추가

CodeWiz 일부 블록 수정, 추가

---

src/playground/blocks/hardware/block_castarter_v2.js

수정 사항 :
-각 블럭 타이틀 생성
-각종 오류 및 안전성 개선

여러 오류사항 수정 및 개선 사항 수정

---

extern/util/CanvasInput.js
extern/util/CanvasInputOrg.js
src/class/pixi/etc/PIXICanvasInput.js
src/class/stage.js

[#4355](https://oss.navercorp.com/entry/entry2/issues/4355)

이슈 4355 처리

---

src/class/pixi/etc/PIXIBrushAdaptor.ts
src/graphicEngine/GEHelper.ts

[#4500](https://oss.navercorp.com/entry/entry2/issues/4500)
[참고](https://stackoverflow.com/questions/50221078/how-to-change-style-of-lines-using-pixi-js-graphics)

[#4500] 부스트모드 '붓의 색을 ~(으)로 정하기' 블록이 의도대로 동작하지 않는 현상

---

src/playground/blocks/hardware/block_choco.js

쪼코 소리내기-음계 추가

---

src/playground/blocks/block_looks.js

[#2142](https://oss.navercorp.com/entry/entry2/issues/2142)

[#2142] 글상자 오브젝트에 생김새 > 말하기 블록 노출되도록 수정

---

src/class/entity.js

[#2130](https://oss.navercorp.com/entry/entry2/issues/2130)
1. webgl(pixijs) 사용중이고 lineBreak 사용중일때  offset 5.9 추가 적용

[4.11.0][#2130] 이슈 2130 처리

---

src/class/dialog.ts

[#2131](https://oss.navercorp.com/entry/entry2/issues/2131)

[#2131] 이슈 2131 처리

---

src/playground/block_view.js

[#4597](https://oss.navercorp.com/entry/entry2/issues/4597)

[block_view] magnet에 빠진 속성들 추가

---

src/playground/blocks/hardware/block_choco.js

- 하드웨어 '쪼코'의 변경사항을 다음 배포로 연장되어 revert합니다.
This reverts commit e52208e46a88dd8f4bc718ffa6b3a5e20f8b5dde.

Revert "쪼코 소리내기-음계 추가"

---

src/playground/workspace.js

[#4584](https://oss.navercorp.com/entry/entry2/issues/4584)
잘라내기 할때 destroyBlock 처리로 변경

이슈 4584 처리

---

package-lock.json
package.json
yarn.lock

Reverts entrylabs/entryjs#2229

Revert "Bump karma from 4.4.1 to 6.3.16"

---

src/class/object.js

[#4677](https://oss.navercorp.com/entry/entry2/issues/4677)

이슈 4677 처리

---

src/class/object.js

[#4773](https://oss.navercorp.com/entry/entry2/issues/4773)

[#4773][object] 오브젝트의 순서를 바꾸는 메뉴 추가

---

src/playground/blocks/hardware/block_castarter_v2.js

2세대 코딩어레이 스타터 신규 하드웨어 추가
-코딩어레이 328PB 보드

2세대 코딩어레이 스타터 하드웨어 추가

---

src/class/engine.js

[#4082](https://oss.navercorp.com/entry/entry2/issues/4082)

이슈 4082 처리

---

src/playground/workspace.js

[#4803](https://oss.navercorp.com/entry/entry2/issues/4803)

[#4803] 블록 잘라내기 실행 시 아래 블록까지 제거되도록 수정

---

src/playground/board.js

[#4699](https://oss.navercorp.com/entry/entry2/issues/4699)

4699 리오픈 이슈 처리

---

src/playground/blocks/hardware/block_castarter_v2.js

안녕하세요~
코딩어레이입니다.
2세대 코딩어레이 스타터 나노보드 하드웨어 추가 등록 요청드립니다.
감사합니다.

2세대 코딩어레이 스타터 나노보드 하드웨어 추가 등록

---

src/util/videoUtils.ts
src/util/workers/video.worker.ts

- 맥, 윈도우, 웹(크롬, 사파리)에서 테스트하였습니다.

[4.14.0][#3956] 오프라인에서 인공지능 비디오 블록의 '얼굴'감지가 되지 않는 이슈 수정

---

src/playground/blocks/hardware/block_mechatro.js

entry-hw쪽 빌드파일에서 연결에 문제가 있어 이번 배포에서 revert합니다.
This reverts commit 2198d90aaf0328043904102bef99923382e1ef83, reversing
changes made to f0146f4ac22f76e824806af17718da8e9d690544.

[4.14.0] 메카트로 우노,나노 revert 

---

src/playground/blocks/hardware/block_iCOBOT.js

iCOBOT 모터 및 센서 값 받아오는 부분 문제 파악하여 수정완료

iCOBOT 엔트리 코드 변경(수정)_20220720

---

.eslintrc
package.json
src/class/DataTable.js
src/extensions/dmet.js
src/playground/blocks/block_analysis.js
yarn.lock

[#5082](https://oss.navercorp.com/entry/entry2/issues/5082)

[table] 테이블 블록에서 알파벳을 입력해 열을 지정 할 수 있도록 수정

---

src/class/stage.js

[#5050](https://oss.navercorp.com/entry/entry2/issues/5050)

[#5050] stage에 videoContainer 필드 추가

---

src/playground/block_entry.js
src/playground/executors.js

function_general executor 제어방식 변경

---

src/class/engine.js
src/playground/block_entry.js
src/playground/code.js
src/playground/executors.js

Co-authored-by: Youngduk Park <0duck@kakao.com>
Co-authored-by: Tnks2U <84176658+Tnks2U@users.noreply.github.com>
Co-authored-by: JaehyeonSK <cjh7163@naver.com>
Co-authored-by: usbsync <usbsync@nts-corp.com>

함수에서 비동기 블록을 호출하지 않을때 퍼포먼스 개선 (#2328)

---

src/playground/code.js

[hotfix][#5132]

---

src/playground/code.js

[hotfix][#5132] 비동기 블록이 포함 된 함수 블록 실행 시, 작품 정지하기 기능이 동작하지 않음

---

src/playground/blocks/hardware/block_mechatro.js

A2,A3,A4,A5 포트 디지털 입출력 가능하도록 기능 확장
아날로그 입력 판단 블록 추가
센서값 출력 안정화
초음파 센서 초기화 문제 해결
온도 센서값 정수화
모터, 톤 동시 사용 시 충돌 문제 해결
모터, 톤 동시 사용 시 후행 명령만 실행
톤 성능 개선
같은 음 연속 사용 시 연음되는 현상 해결, 음간 간격 삽입으로 소리 구분

[Mechatro] 디지털 포트 확장 및 센서 오류 개선 등

---

src/playground/blocks/block_analysis.js

[#5146](https://oss.navercorp.com/entry/entry2/issues/5146)

[table] 테이블의 행의 개수가 1개 작은 수로 처리됨

---

src/playground/blocks/hardware/block_iCOBOT.js
src/playground/blocks/hardware/block_mechatro.js

[# 5185](https://oss.navercorp.com/entry/entry2/issues/5185)
- 이번 마일스톤은 하드웨어 '메카트로 우노&나노'의 블록파일 이외에는 변경사항이 없습니다.

[4.16.0] 하드웨어 1.9.33 버전 PR

---

src/class/function.js
src/playground/block.js
src/playground/board.js

[#5163](https://oss.navercorp.com/entry/entry2/issues/5163)

add assemble

---

src/playground/blocks/hardware/block_0uboard.js

공유보드(표쌤코딩) 추가

---

src/playground/blocks/hardware/block_iCOBOT.js

iCOBOT 온습도 센서 관련 수정하였습니다.
entry-hardware 부분도 함께 수정하였습니다.

iCOBOT 버그 수정_220921

---

extern/util/static.js
src/class/DataTable.js
src/class/source/DataTableSource.js
src/playground/blocks/block_analysis.js

[#5323](https://oss.navercorp.com/entry/entry2/issues/5323)

[#5323] 테이블의 현재 상태를 저장하기, 테이블 창 열기 블록을 추가

---

src/graphicEngine/GEHelper.ts
src/playground/block_entry.js
src/playground/blocks/block_ai_utilize_video.js
src/playground/blocks/index.js
src/util/videoUtils.ts

[#5333](https://oss.navercorp.com/entry/entry2/issues/5333)
1. AI_UTILIZE_BLOCK video에 destory상황 추가

이슈 5333 처리

---

src/playground/blocks/hardware/block_iCOBOT.js

- 습도와 온도 센서 값을 이용하여 불쾌지수를 계산하는 계산 블록을 추가하였습니다.
- 블록의 순서를 재배치 하였습니다.
- 블록에 사용하는 변수명을 작성해주었습니다.
- 블록별 설명하는 부분을 추가하였습니다.(Help)
- Monitor 부분을 작성할 수 있는 것으로 보여, 작성 중에 있습니다.
-> 센서 값을 어떻게 변화시키는지 몰라, 현재, 센서 위치만 보이도록 작성해놓은 상태입니다..

20221018_불쾌지수 블럭 추가 및 블럭 설명 추가 및 Monitor부분 수정중

---

src/class/variable_container.js

[#5288](https://oss.navercorp.com/entry/entry2/issues/5288)

이슈 5288 처리

---

src/class/variable_container.js

[#5269](https://oss.navercorp.com/entry/entry2/issues/5269)

이슈 5269 처리

---

src/class/DataTable.js
src/playground/blocks/block_analysis.js

[#5323](https://oss.navercorp.com/entry/entry2/issues/5323)

[#5323][데이터 분석] 테이블의 현재 상태를 저장하기, 테이블 창 열기 블록을 추가

---

src/class/variable_container.js

[#5282](https://oss.navercorp.com/entry/entry2/issues/5282)

이슈 5282 처리

---

src/class/AILearning.js

모듈명에 오타가 있어서 빌드가 실패했습니다. 이 브랜치로 빌드되는것 확인했습니다.

[#5068] 모듈명 오타수정

---

src/playground/blocks/hardware/block_robotry_robit_stage.js

- 하드웨어 제어로직, 펌웨어 변경점 없음
- 블럭코드의 센서 값이 좀 더 부드럽게 동작 하도록 수정
- 소리센서 값의 변화를 보다 더 인지하기 쉽게 변화하도록 수정

[로보트리] 로빗 무대 블록 코드 센서 값이 좀 더 부드럽게 인식되도록 수정

---

src/class/learning/DecisionTree.js
src/class/learning/LogisticRegression.js
src/class/learning/Svm.js

https://oss.navercorp.com/entry/entry2/issues/5068#issuecomment-9042893

[4.19.0][5068] svm, dt 학습판단블록 수정

---

src/playground/blocks/block_func.js

[4.19.0] entry hw PR

---

package.json
yarn.lock

edit actions eslint

---

src/playground/blocks/block_looks.js

[#5662](https://oss.navercorp.com/entry/entry2/issues/5662)
dialog_time이 계속 만들어 지는것이 아니라 remove_dialog로 제거 될수 있도록 처리 사이드 이펙트는 체크 필요

이슈 5662 처리

---

src/playground/blocks/hardware/block_microbit2.js
src/playground/blocks/hardwareLite/block_microbit2_lite.js

- https://oss.navercorp.com/entry/entry2/issues/5643

[#5643] 마이크로비트 버튼이벤트 추가

---

src/class/playground.js

[#5181](https://oss.navercorp.com/entry/entry2/issues/5181)

모드 변경시 선택된 오브젝트정보로 board object title 변경

---

src/class/container.js

1. switch 문에서 break이 빠져 잘못된 결과값 리턴 - break 추가
[#5732](https://oss.navercorp.com/entry/entry2/issues/5732)

이슈 5732 처리

---

src/util/videoUtils.ts

[#5733](https://oss.navercorp.com/entry/entry2/issues/5733)
1. turnOnWebcam 처리할때 isChanged값이 없을 경우에만 정방향 세팅하도록 처리

이슈 5733 처리

---

src/playground/blocks/hardware/block_iCOBOT.js

모터가 회전하는 동안 기다리는 블록을 추가하였습니다.
현재, 저희가 하드웨어 수정중에 있어, 다시 하드웨어를 보내드리지 못해, 엔트리 측에서 테스트 진행이 어려운것으로 알고 있습니다.
빠른 시일내로 하드웨어 샘플을 보내드릴 수 있도록 하겠습니다.
감사합니다.

[20230216]Change Buzzer and Digital Pin

---

src/playground/blocks/hardware/block_iCOBOT.js

이번에 새로 추가한 기다리기 블럭에 문제가 있어 수정하였습니다.
제대로 확인하지 못하고 업로드 하여 죄송합니다..

[20230221]기다리기 블럭 에러 수정

---

src/util/videoUtils.ts

[#5733](https://oss.navercorp.com/entry/entry2/issues/5733)

5733 추가 요청 처리

---

src/playground/blocks/hardware/block_iCOBOT.js

어제 수정하였던 wait motor 블럭 관련하여, 보기에서 어떤 구동을 하고 있는 상태인지 고르게 하기 보다는, 변수를 이용하여 현재 사용하고 있는 블럭을 정하도록 하였습니다.
여러번 수정하여 죄송합니다...ㅠ

[20230222]-Change wait motor

---

src/css/components/scene.less
src/css/static.less

[#5840](https://oss.navercorp.com/entry/entry2/issues/5840)

이슈 5840 처리

---

src/playground/blocks/hardware/block_aibot.js

AIBOT 제어 블록 추가

---

src/playground/blocks/hardwareLite/metadata_choco_lite.json
src/playground/blocks/hardwareLite/metadata_neo_lite.json
src/playground/blocks/hardwareLite/metadata_neobot_purple_lite.json
src/playground/blocks/hardwareLite/metadata_neobot_soco_lite.json
src/playground/blocks/hardwareLite/metadata_neobot_thinkcar_lite.json

https://oss.navercorp.com/entry/entry2/issues/6145#issuecomment-10153745

[6145][4.24.0]lang: 웹연결 하드웨어 제조사명 변경

---

src/playground/blocks/hardware/block_0uboard.js
src/playground/blocks/hardwareLite/block_microbit2_lite.js

공유보드 업데이트 2305

---

src/playground/blocks/hardware/block_KKMOO.js

*동작 상태 판단 블록의 딜레이 시간을 수정 하였습니다.

230512_딜레이시간 변경

---

src/class/function.js
src/playground/blocks/block_func.js

[#6461](https://oss.navercorp.com/entry/entry2/issues/6461)

이슈 6461 처리

---

src/class/learning/DecisionTree.js
src/class/learning/LogisticRegression.js
src/class/learning/Svm.js
src/class/learning/Utils.ts

issue/6737 

---

src/playground/blocks/hardware/block_asomekit.js

AsomeKit 등록

---

src/class/object.js

[#6686](https://oss.navercorp.com/entry/entry2/issues/6686)

복제본 앞뒤 순서 보정

---

src/class/entryModuleLoader.ts
src/class/hardware/hardwareMonitor.ts
src/class/hw.ts
src/class/hw_lite.ts
src/class/intro.ts
src/playground/block_menu.ts
types/window.d.ts

https://github.com/entrylabs/entryjs/pull/2551/files#r1315270961

[#7013] refactor: window 하위 객체 globlal로 선언

---

src/playground/block_menu.ts

[#6968](https://oss.navercorp.com/entry/entry2/issues/6968)

beta 리스트에서 데이터분석, 인공지능 카테고리 제거

---

src/playground/blocks/block_judgement.js

[#7028](https://oss.navercorp.com/entry/entry2/issues/7028)

이슈 7028 처리

---

src/class/engine.js
src/class/variable/sttVariable.js
src/class/variable_container.js
src/util/audioUtils.js
src/util/utils.js

[#2135](https://oss.navercorp.com/entry/entry2/issues/2135)
1. 상세화면 실행 오류 수정
2. 색상 `#8222ff` 으로 변경

2135 추가 이슈 처리

---

src/playground/blocks/hardware/block_neo.js
src/playground/blocks/hardwareLite/block_neo_lite.js

블럭 순서 변경 및 타이틀 추가
Neo 센서 블럭 추가
Neo 자율주차 로직 변경

[네오피아] 버그수정

---

src/playground/blocks/hardware/block_proboconnect.js

DC모터 블록 추가.
S모터 블록추가.
RGB LED 추가.
멀티키, 나침반, 3가속, 분배기 추가.
멜로디 추가.

230824 block update

---

src/class/variable/sttVariable.js

[#7148](https://oss.navercorp.com/entry/entry2/issues/7148)

sttTypes을 체크할때 getBlocks에 들어 있는 블록을 기준으로 할수 있도록 수정

---

src/playground/blocks/block_judgement.js

https://oss.navercorp.com/entry/entry2/issues/5764#issuecomment-11546849

[#5764] 판별블록 파라미터 추가

---

src/playground/blocks/block_judgement.js

https://oss.navercorp.com/entry/entry2/issues/5764#issuecomment-11674592

[#5764] is_type 블럭 arrow 설정 추가

---

src/playground/blocks/block_sound.js

[#7258](https://oss.navercorp.com/entry/entry2/issues/7258)

addSoundInstances에 sprite추가

---

src/util/utils.js

pauseSoundInstances, recoverSoundInstances 할때 bgmInstance도 paused되도록 처리

배경음악 동작 수정

---

extern/face-landmarker.worker.js
extern/face-landmarker2.worker.js
extern/gesture-recognition.worker.js
extern/object-detector.worker.js
extern/pose-landmarker.worker.js
extern/vision.worker.js
src/util/mediaPipeUtils.ts
src/util/utils.js

https://oss.navercorp.com/entry/entry2/issues/7356
6736이슈를 오프라인에 대응하기 위한 작업입니다.
이 PR은 바로 develop에 머지될 필욘 없습니다만, 리뷰를 위해 미리 PR드립니다.
워커에서 self.location.pathname 사용시, 로컬서버환경에서는 '/lib/entry-js/extern/본인파일명' 으로 나오게 됩니다.
로컬서버환경과 오프라인환경 모두 정상동작 확인했습니다만, **운영서버에서 문제가 될 것 같다면 공유 부탁드립니다**.

인공지능 블럭 오프라인 대응

---

src/playground/blocks/hardware/block_KKMOO.js

231122_동작개선 및 블럭 추가

---

src/playground/blocks/hardware/block_runcoding.js

temp block add

---

src/util/utils.js

[#7258](https://oss.navercorp.com/entry/entry2/issues/7258)

일시 정지 후 다시 시작할때 playbackRateValue 재적용 하기

---

src/playground/blocks/hardware/block_asomebot.js
src/playground/blocks/hardware/block_asomekit.js

**AsomeBot**
LED 블록 추가
블록 수정
**AsomeKit**
블록 수정

[AsomeBot, AsomeKit] 블록 추가 및 수정

---

src/class/playground.js
src/class/sound.ts

[#2145](https://oss.navercorp.com/entry/entry2/issues/2145)

2145 추가 이슈 처리

---

src/playground/blocks/hardware/block_etkit.js

이티키트 블록 업데이트

---

src/playground/blocks/block_func.js

[#7937](https://oss.navercorp.com/entry/entry2/issues/7937)
#2652

add removeExecutor

---

src/playground/blocks/block_func.js
src/playground/code.js

[#8017](https://oss.navercorp.com/entry/entry2/issues/8017)

getParams => values로 이동

---

src/util/mediaPipeUtils.ts
src/util/workers/newmotion.worker.ts
types/entry.d.ts

[#8013](https://oss.navercorp.com/entry/entry2/issues/8013)

이슈 8013 처리

---

src/playground/blocks/block_calc.js

#2665 
[#8054](https://oss.navercorp.com/entry/entry2/issues/8054)

불필요한 async 제거

---

src/command/commands/object.js

#2674 
[#8053](https://oss.navercorp.com/entry/entry2/issues/8053)

objectAddSound 시 selectedSound가 없으면 주입

---

src/playground/blocks/hardware/block_jinirobot_toybot.js

setZero 호출 시 ToyBot 정지 기능 추가
블록간 지연 코드 개선
아날로그 입력값 블록 리턴값을 % 단위로 수정
음표 블록에 쉼표 기능 추가
음표 블록에 점 이분음표, 사분음표 박자 기능 추가
효과음 블록에 6번~12번 기능 삭제
서보모터 기본위치 제어 아이콘 누락 수정
hw 호출 전 코드 개선
입력범위 초과 시 처리 코드 수정

ToyBot 블록 개선

---

src/playground/blocks/hardware/block_ITPLE_board.js

잇플 보드 모터 핀 번호 변경

---

src/class/hardware/bluetoothServices/index.ts
src/class/hardware/bluetoothServices/services/accelerometer.ts
src/class/hardware/bluetoothServices/services/button.ts
src/class/hardware/bluetoothServices/services/device-information.ts
src/class/hardware/bluetoothServices/services/dfu-control.ts
src/class/hardware/bluetoothServices/services/event.ts
src/class/hardware/bluetoothServices/services/io-pin.ts
src/class/hardware/bluetoothServices/services/led.ts
src/class/hardware/bluetoothServices/services/magnetometer.ts
src/class/hardware/bluetoothServices/services/temperature.ts
src/class/hardware/bluetoothServices/services/uart.ts
src/class/hardware/webBluetoothConnector.ts

https://oss.navercorp.com/entry/entry2/issues/8023
- 키값으로 사용하는 서비스함수의 name값을 string으로 주입

[4.34.0][HW] minify과정에서 웹 ble관련 코드 버그 수정

---

src/playground/blocks/block_func.js

[#8017](https://oss.navercorp.com/entry/entry2/issues/8017)

이슈 8017 처리

---

extern/face-landmarker.worker.js
src/util/mediaPipeUtils.ts

[#8160](https://oss.navercorp.com/entry/entry2/issues/8160)

이슈 8160 처리

---

src/playground/blocks/hardware/block_robotis.js
src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js

- 로봇아이(AI) 블록 개선
- LCD 깜박이기 블록 추가
- RB-100이 보내주는 auto-report 패킷으로 받은 데이터 활용
- write 패킷 기본 딜레이 15ms -> 50ms
- DXL 각도값만 사용

로봇아이 블록 수정

---

src/playground/blocks/hardware/block_iCOBOT.js

하드웨어 통신 프로토콜을 변경하면서, 변경된 코드에 맞게 블록 내용도 변경하였습니다.

240417-Change Protocol

---

images/entry_scroll_02.svg
images/entry_scroll_03.svg
src/class/playground.js
src/css/components/block_menu.less
src/css/components/board.less
src/css/components/playground.less
src/playground/block_menu.ts
src/util/utils.js

[#8141](https://oss.navercorp.com/entry/entry2/issues/8141)

이슈 8141 처리

---

src/playground/blocks/block_brush.js

[#8184](https://oss.navercorp.com/entry/entry2/issues/8184)

이슈 8184 처리

---

src/playground/blocks/block_calc.js

[#8185](https://oss.navercorp.com/entry/entry2/issues/8185)

이슈 8185 처리

---

.eslintrc
src/class/playground.js
src/css/components/board.less

[#8141](https://oss.navercorp.com/entry/entry2/issues/8141)

8141 추가 이슈 처리

---

src/playground/blocks/hardware/block_asomekit.js

AsomeKit 확장 모듈 블록 추가

---

src/class/LiterallycanvasPainter.js
src/class/container.js
src/class/object.js
src/class/painter.js
src/class/playground.js
src/class/project.js
src/class/sound.ts
src/command/commands/object.js
src/util/utils.js

Reverts entrylabs/entryjs#2761

Revert "운영반영"

---

src/playground/blocks/hardware/block_iboard.js

다시 한번 수정했습니다.
많이 해보지 않아 여러번 번거롭게 해드려 죄송합니다.

iboard의 블록이 보이지 않는 문제 수정

---

src/playground/blocks/hardware/block_robotisRBCar.js
src/playground/blocks/hardware/block_robotisRBHumanoid.js

블록 파라미터 번호 수정

---

src/class/function.js
src/playground/blocks/block_func.js
src/playground/executors.js
src/util/utils.js

- 함수 블록에서 에러 발생시 정상적으로 블록 표시해주도록 변경
- toggleStop이 여러번 호출되지 않도록 처리

이슈 8447 처리

---

src/playground/blocks/hardware/block_jinirobot_toybot.js

토이봇 속도 드랍다운 블럭을 1-5까지 표시되도록 변경함.

토이봇 속도 1-5까지로 변경

---

src/playground/blocks/hardware/block_arduino_ext.js
src/playground/blocks/hardware/block_arduino_nano.js

https://oss.navercorp.com/entry/entry2/issues/8497

[8497 ]아두이노 확장/나노 다국어 수정

---

src/playground/blocks/hardware/block_altino_lite.js

Add block to reset AltinoLite's IR sensor

 Update block_altino_lite.js

---

src/playground/blocks/hardware/block_neo_cannon.js
src/playground/blocks/hardwareLite/block_neo_cannon_lite.js

- 네오캐논 네오픽셀 5개 블록 추가
- 네오캐논 네오픽셀 5개 블록 추가
- 네오픽셀 로직 추가

네오캐논 블록 추가

---

src/playground/blocks/hardware/block_alux_nemo.js

에이럭스 네모 등록

---

src/playground/blocks/hardware/block_proboconnect.js

프로보커넥트 블록 추가

---

extern/lang/ko.js
src/class/hardware/webUsbFlasher.ts
src/playground/block_entry.js
src/playground/blocks/hardware/block_microbit2.js
src/playground/blocks/hardwareLite/block_microbit2_lite.js
src/playground/blocks/hardwareLite/block_microbit2ble_lite.js

- 펌웨어 설치 함수에 콜백함수 추가
- 마이크로비트 블럭 구분선 제거
https://oss.navercorp.com/entry/entry2/issues/7700#issuecomment-14166171

[4.40.0] 하드웨어 UX 개선

---

src/playground/blocks/hardware/block_alux_nemo.js

네모 확장 블록 수정
- 센서 설정 블록 센서 인덱스 수정
- 센서 값 반환 블록 변수 수정
- 종류별 값 반환 블록 변수 수정

에이럭스 네모 확장 블록 수정

---

src/playground/blocks/hardware/block_handino.js

수어: ㄱ,ㄴ,ㄷ...ㅍ,ㅎ에 대한 손가락 표현
산수: 두 정수를 사직연산 결과에 대한 손가락 표현

수어및 산수 블럭 추가

---

src/playground/blocks/hardware/block_alux_technic.js

'테크닉 파워', '테크닉 일반' 공용 신규 블록입니다.

에이럭스 테크닉 파워, 일반 신규 블록 생성

---

src/playground/blocks/hardware/block_altino.js
src/playground/blocks/hardware/block_altino_lite.js

Add IR sensor reset function block for Altino & Edit block shape for Altino and Altino Lite

Add IR sensor reset function block for Altino & Edit block shape for Altino and Altino Lite

---

src/playground/blocks/hardware/block_zumiMini.js

로보링크 주미 미니 블록 수정

---

src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js
src/playground/blocks/hardware/block_whalesbot_eagle_1001.js
src/playground/blocks/hardwareLite/block_robotis_robotai_lite.js

- 로봇아이 AI 블록 문구 수정
- 왼쪽바퀴 -> 왼쪽바퀴(52)
- 오른쪽바퀴 -> 오른쪽바퀴(52)
- 카메라 인식 형태항목에 "표정" 추가

로봇아이 AI 블록 문구 수정

---

src/playground/blocks/hardware/block_jcboard.js
src/playground/blocks/hardware/block_robodog.js

로보독(사족로봇) 지원

---

src/playground/blocks/hardware/block_avatarbot.js

uart serial 통신 모델을 bluetooth ssp 모델로 변경 작업 완료.

bluetooth ssp function complete

---

src/playground/blocks/hardware/block_robotori.js

로보토리 하드웨어 관련해서 
- 기존의 하드웨어 핀 번호를 하드웨어에 인쇄된 번호를 따르도록 수정
- 기존 DC 모터 회전 제어 블록와 별개로 전진, 후진 블록 추가
- DC 모터 정지 블록 추가
- 신규 온도, 가스 측정 센서 블록 추가

로보토리 하드웨어 블록 내용 추가 및 핀 번호 수정

---

src/playground/block_entry.js

[#7957](https://oss.navercorp.com/entry/entry2/issues/7957)

[WIP] issue/7957

---

extern/util/static.js
src/playground/blocks/block_flow.js
src/playground/executors.js

[#8642](https://oss.navercorp.com/entry/entry2/issues/8642)

issue 8642

---

src/playground/executors.js

[#9109](https://oss.navercorp.com/entry/entry2/issues/9109)

issue/9109

---

src/playground/blocks/hardware/block_robotisRBKoala.js

코알라봇 lite 변경사항 hw에 적용
- 카메라 관련 변수명/함수명 변경
- game_character icon 블록 추가
- 엔트리 정지시 초기화 과정은 유지하되 코알라 얼굴 표시

코알라 lite 변경사항 hw에 적용

---

src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js

로봇아이 lite 변경사항 hw에 적용
- 카메라 관련 변수명/함수명 변경
- game_character icon 블록 추가

로봇아이 lite 변경사항 hw에 적용

---

src/playground/blocks/hardware/block_whalesbot_eagle_1001.js

add blocks for sensor, light

---

src/playground/blocks/hardware/block_elio.js

온도 습도 수분 블럭 추가

---

src/playground/blocks/hardware/block_smartCodingHouse.js

block_smartCodingHouse.js 신청드립니다Add files via upload

block_smartCodingHouse.js 신청드립니다Add files via upload

---

src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js

로봇아이 블록 문구 수정

---

src/playground/blocks/hardware/block_timbo.js

Add Timborobot

---

src/playground/blocks/hardwareLite/block_alux_connect_lite.js
src/playground/blocks/hardwareLite/metadata_alux_connect_lite.json

- 리모컨 이벤트 오류 수정
- 디지털 이벤트 오류 수정
- 무한회전센서 값 설정 오류 수정

ConnectLite 오류 수정

---

src/playground/blocks/hardwareLite/block_alux_teachnic_power_lite.js
src/playground/blocks/hardwareLite/metadata_alux_teachnic_power_lite.json

- 리모컨 이벤트 오류 수정
- 디지털 이벤트 오류 수정
- 무한회전 센서값 설정 오류 수정

Technicpowerlite 오류 수정

---

src/playground/blocks/hardwareLite/block_alux_teachnic_normal_lite.js
src/playground/blocks/hardwareLite/metadata_alux_teachnic_normal_lite.json

- 리모컨 이벤트 오류 수정
- 디지털 이벤트 오류 수정
- 무한회전센서 값 설정 오류 수정

TechnicnormalLite 오류 수정

---

src/playground/blocks/hardware/block_timbo.js

Timbo_Queen_Stop, Timbo_Motion_Stop 로직 변경

팀보로봇 블록 로직 변경

---

src/playground/blocks/hardwareLite/block_cocodron_controller_Lite.js
src/playground/blocks/hardwareLite/metadata_cocodron_controller_Lite.json

- block_cocodron_controller_Lite.js 명령어 개선
- 대기시간 조정
- ja(일본어) 추가
- metadata 조종기기->조종기 변경

기타 수정 및 일본어 반영
