entrylabs/entryjs

- extern/util/static.js
소리탭 블록사이에 있는 가로선의 위치를 수정.
재생하기와 기다리기 영역으로 분리.
[#1948](https://github.com/boolgom/Entry/issues/1948)
> Entry issue #1948

- src/workspace/block_entry.js
네오봇 요구사항 입니다.
1. FND블록
FND (00) 출력
아이들이 16진수 이해를 못할거 같습니다. 타이핑으로 0~99까지 입력한 것을 출력하도록 해야겠습니다.(0~99까지의 정수)
블록설명: FND로 0~99 까지의 숫자를 표시할 수 있습니다.
2. 입력범위 변환명령 수정
[1번포트 ] 값의 범위를 (0)~(255)에서 (0)~(100)(으)로 변환
블록설명: 선택한 포트 입력값의 변화를 특정범위의 값으로 표현범위를 조절할 수 있습니다.
> 네오봇 요구사항 반영.

- README.md
I'm trying to get entryjs running locally, and haven't succeeded so far. While trying to make sure the code I run is the same as yours, I checked which versions of libraries were used on the play-entry website, and added them to the README.md.
I suggest you supply a bower.json file or similar, with proper semver specifications, so that other developers have an easier time knowing which library versions are safe to use and not.
> Add safe dependency versions to README.md

- src/workspace/block_entry.js
ref boolgom/Entry#4218
기존 state를 Entry.ArduinoExt.BlockState에서 관리하여 block scope간 state를 공유하여 실제 값 처리 할때 우선순위에 따라 다르게 처리 되던 문제
Entry.ArduinoExt.BlockState에서 executor의 scope로 변경하여 executor별 state값을 가질수 있도록 수정.
> 아두이노 확장 블록 state공유 문제 해결.

- src/workspace/block_entry.js
boolgom/Entry#3779
아두이노 text블록 색상 변경
#00979D -> #FFD974
> issue/3779 (3.1.0 마일스톤)

- src/entry.js
- https://github.com/boolgom/Entry/issues/7101
- 사운드 파일에서 오류 발생시(Uncaught DOMException: Unable to decode audio data) 해당 사운드외 다른 사운드까지 재생이 안되는 오류를 방지하기 위한 방어코드.
> issue Entry/#7101 소리재생불가 오류관련

- src/playground.js
boolgom/Entry#7082 처리
장면에 오브젝트가 비어 있는 경우 currentObject의 변화가 발생하지 않음.
이 상태에서 다시 오브젝트가 존재하는 장면으로 이동할 경우 currentObject와 현재 장면의 첫번째 
오브젝트를 비교 하게되는데 해당 비교에서 오브젝트가 동일 할 경우 
모양 및 소리 탭의 리스트를 갱신 하지 않는 문제.
현재 선택된 오브젝트와 장면의 첫번째 오브젝트가 동일해도 실제 리스트에 해당 아이템이 없는 경우에는 
강제로 아이템을 그리도록 수정함.
> 이슈 7082 처리

- src/function.js
ref https://github.com/boolgom/Entry/issues/7112
** [WS] 함수 만들기 > 이름 블록에 문자/숫자값 블록과 판단값 블록을 조립 > 만든 블록 복사, 붙여넣기 > 함수에 블록 조립 > 넘버링 오류
> [3.6.0] set copyable false for fieldLabel block

- src/stage.js
- src/util/utils.js
- src/workspace/board.js
IOS 디바이스
(애플 모바일 디바이스)
에서 scroll, resize, orientationchange 이벤트 발생시
실제 그려질 UI와 계산된 UI가 달라 일부 요소들의 좌표가 잘못 계산되어짐.
IOS환경이면 1초 주기로 돌면서 변경이 Resize요소가 발생하면 Resize Event를 Notify하도록 수정
그리고 기존에 scroll발생시 Resize Notify가 너무 많이 발생되던 부분을
debounce처리로 빈도수를 줄임.
> ios 좌표 관련 버그 수정

- src/command/commands/textbox.js
- src/playground.js
- src/util/static.js
boolgom/Entry#7297 연관 이슈 처리
기본적으로 텍스트 수정에 대하여 undoStack을 추가 할수 있도록 처리
오프라인에서 변경 사항 체크를 undoStack을 기준으로 하기 때문에 해당 작업 추가함.
> textbox editText command 추가

- src/workspace/block_menu.js
@boolgom 
boolgom/Entry#5443 이슈를 처리 하기 위한 #789 PR로 인해 발생한 사이드 이펙트를 수정하는 PR 입니다.
필요한 라인이 지워져서 _getSortedBlocks 함수가 동작하지 않는 버그를 수정하였습니다.
> 5443 이슈 처리중 발생한 사이드 이펙트 처리

- scripts/build.sh
이번 교과형 부터 travis 빌드시 포함되어야 될 block_entry_mini 파일이
포함되지 않아 블록이 정상적으로 노출되지 않는 상태에 있었음.
해당 파일 빌드에 포함하여 이상없도록 수정.
> add block_entry_mini.js

- src/workspace/block_view.js
https://github.com/boolgom/Entry/issues/7749
** [WS] 도움말로 초시계 관련 블럭들을 선택 한 후 다른 블록 탭으로 이동 시 초시계 블럭 생성 없이 초시계 기능이 추가 되는 현상
** 블록 도움말의 경우 초시게 view가 생성되지 않도록 함
> [3.9.0] timerView bug fix

- src/workspace/workspace.js
boolgom/Entry#7818
Entry.init 할 당시에 options 값의 textCodingEnable 값이 false인경우
단축키인 `Ctrl + [`과 `Ctrl + ]`의 동작을 막고
기본적으로 setMode로 모드 전환시 VimBorad로의 전환을 막음.
> 이슈 7818 처리

- src/entity.js
https://github.com/boolgom/Entry/issues/8123
** [WS] 글상자 오브젝트 생성 시 밑줄 효과가 적용 되지 않음 #8123
> text object underline initialize

- src/command/commands/block.js
https://oss.navercorp.com/entry/Entry/issues/8890
블록 thread에서 바로 쓰레기통을 삭제하는 액션할때
destory가 2번 호출되어 오류가 발생하는 문제 수정.
> issue 8890 처리

- src/playground/block_view.js
- src/playground/thread_view.js
블럭 파라미터의 변수변경 로직이 재귀적으로 동작하도록 수정
- 블럭 파라미터의 파라미터가 변수블럭인 경우에도 로직이 닿을 수 있도록 수정
> [#9132] 변수명을 변경했을 때 조립된 변수값블록의 변수명이 변경되지 않는 오류

- src/playground/blocks/index.js
- BitBlock 보드의 블록을 Entry.Arduino 에서 Entry.ArduinoExt 로  ([entryjs]/src/playground/blocks/index.js)
- entry-hw 의 bitblock.json과 bitblock.js 파일도 변경됨 ([entry-hw]/app/modules)
> BitBlock 확장블록 추가를 위해, ArduinoExt로 변경

- extern/util/static_mini.js
워크스페이스 실과형 
판단카테고리  기본 노출 블록 추가(type=workspace 와 동일)
- 참 그리고 참
- 참 또는 거짓
- 참 (이)가 아니다
> Issue/9582 워크스페이스 실과형 기본 블록노출 추가

- src/playground/board.js
https://oss.navercorp.com/entry/Entry/issues/9810
undo/ redo 동작 오류
- 화면에 보이는 순서로 스레드 순서를 조절하여 발생하는 현상
- 블록이 겹쳐져있는 상태에서 드래그로 끼워넣기할때 맨위 블록이 선택 안될 수 있음
- 향후 thread를 index로 처리했던 부분을 id로 수정하게끔 변경해야함
> [hotfix] Issue/9810

- src/playground/skeleton.js
1. skeleton.js
- 이름(function_field_string)
- 숫자/문자(function_field_string)
- 판단값(function_field_boolean)
블록에 대해서 
skeleton.basic_param offsetX값 0 에서 -8로 변경
> Issue/9841 함수블록 위치조정

- src/playground/blocks/block_judgement.js
#block_judgement.js
충돌 체크 함수의 `getRect` 인자를 true -> false 로 바꿈
`true 일때` : 충돌하는 사각형 영역을 리턴
`false 일때 ` : 충돌하는 임의의 점 ( loop 중에 발견된 첫번째 점 ) 을 리턴
`이득` : 적은 수의 loop 를 수행함으로서 성능 향상을 기대
> [충돌체크] 최적화: 충돌 체크 함수의 리턴을 사각형이 아닌, 점으로 리턴받음.

- src/playground/workspace.js
#9999
"블럭"탭 에서만 블럭을 복사하도록 수정함.
> 조립된 블록이 있는 오브젝트에서 블록이 선택된 상태 > 그리기 화면 > 그림 복사 후 붙여넣기 시 블록도 함께 복사 및 붙여넣기 됨 #9999

- src/class/painter.js
- src/util/init.js
entryjs 에서 painterBaseUrl 을 선언하는 부분이 없어 무조건 기본값으로 세팅되는 문제 발생
Entry init options 의 libDir 을 기준으로 literallycanvas-mobile 위치를 선정하도록 수정  
(literallycanvas-mobile 이라는 이름은 기존값에서 유지)
> [issue/10051] Entry.Painter 의 baseUrl 선언절차 수정

- src/class/pixi/plugins/pixiGetChildAt.js
> [#10220] getChildIndex, addChildAt -> throw 안하도록 수정

- src/class/object.js
- masOS의 기본 경로에 공백이 포함되어있어
backgroundImage 속성이 적용되지 않던 문제 수정
> [feature] mac OS offline 의 기본 경로에 포함되는 공백관련 이슈 수정

- src/playground/field/block.js
[#10471](https://oss.navercorp.com/entry/Entry/issues/10471) 처리
조립되어 있는 field블록의 경우 따로 thread가 있지 않고 field블록이 thread 역할을함.
field 블록에 비어 있는 getBlockList, stringify, toJSON 함수를 추가함.
> 이슈 10471 처리

- src/class/playground.js
https://oss.navercorp.com/entryline/web/issues/295
<br>태그 까지 html로 보여주도록 수정.
> [#295] 일본어의 경우 .이 아니라 。로 사용되고 있어 줄바꿈이 적용되지 않고 . 이 추가로 나오는 오류 수정

- src/graphicEngine/GEDragHelper.ts
- 이슈는 A obj mouseUp 후, scene 전환 후 클릭에서 B obj mouseDown
과 A obj pointerupoustide 이벤트가 mouseUp 으로 동작하면서 발생한 이슈
down, (up, outside, cancel) = up 으로 이벤트 등록
down 만 등록 후, down 시 모든 이벤트 활성화
up 시 down 을 제외한 모든 이벤트 비활성화
- 추가로 마우스 위에서 클릭 한 후, 다른 위치에서 마우스 업 되었을때 초기 포인터 위치로 up 이벤트가 발생하도록 처리했습니다. createjs 현재 스펙과 동일하게 맞추기 위함입니다.
> [issue/10513][WebGL] handleDrag 이벤트 구현방식 변경

- src/playground/executors.js
어짜피 throw를 할거라면, 에러 내용이라도 알 수 있도록 catch된 error를 throw 하는게 올다고 생각함요.
> [executor] new Error() 대신 catch된 error throw

- package.json
- tsconfig.json
- webpack_config/common.js
- yarn.lock
- 타입스크립트 빌드로 인한 빌드 속도 저하를 완화
- HardSourceWebpackPlugin 으로 빌드 데이터 캐싱 -> 빌드 속도 상승기대
---
- 아무것도 안한 현재 상태
- 50.70s
- 39.70s
- 38.86s
- 38.21s
- 40.14s
- awesome-typescript-loader (이하 at-loader) 에 useCache: true 옵션 추가
- 39.17s
- 36.01s
- 35.85s
- 35.73s
- 34.93s
- (다시 플래그 삭제 후 일반빌드시 : 38.20s)
- at-loader 에 useCache, transpileOnly, useTranspileModule 옵션 추가
- 31.21s
- 29.42s
- 28.91s
- 29.66s
- 30.40s
- tsconfig.json include 를 현재 ts 적용중인 위치로만 한정
- 27.66s
- 27.86s
- 28.23s
- 28.21s
- 28.28s
- HardSourceWebpackPlugin 추가 + 이전 모든설정 적용
- 43.75s
- 13.43s
- 29.29s
- 22.64s
- 20.88s
- 아래 테스트 후 생각해보니, css 관련 캐시 히트 실패로 발생한 빌드 속도 저하로 보입니다.
- 최종적으로, 모든 플래그 정리 / plugin 추가 / css loader exclude (캐시 히트못함) 후 캐시 전부 삭제후 테스트
- 27.03s
- 13.44s
- 13.47s
- 12.99s
- 13.60s
--- …
> [feature] 빌드 최적화

- src/class/hw_monitor.js
- src/playground/blocks/hardware/block_turtle.js
as-is
- 하드웨어 모듈 Object 내
monitorTemplate property 는 무조건 object 여야 했음.
- 그렇기 때문에 해당 프로퍼티가 사용하는 Lang 다국어 데이터는 setLanguage의 데이터가 적용되기 전 평가되므로 undefined 가 될 수 있음
to-be
- 하드웨어 다국어적용 함수인 setLanguage 적용 후 평가된 데이터를 사용해야 하면 monitorTemplate 프로퍼티의 값을 함수로 작성할 수 있도록 수정
> [Issue/10686] 하드웨어 모니터 템플릿 다국어 적용 정책 수정

- src/css/components/block.less
- src/playground/block_entry.js
- src/playground/skeleton/basic/basic_text_light.js
- basic_text skeleton 이 적용된 블록의 param text 가 multiline 인 경우
실제 box 는 single line 크기로 적용되고있었음
- 그래서 text 아래 블록을 multiline text 가 침범하는 문제
- 특정 구조의 block param 이 multiline 인 경우 height 조정
- font-weight: bold 가 아닌 text skeleton 추가
- 해당 로직은 text_skeleton 으로 모은 후 스타일 적용으로 개선필요
> [issue/line/33] basic_text skeleton 내 multiline 적용 외 1

- src/class/variable_container.js
https://oss.navercorp.com/entryline/lineentry/issues/140
- invisibleCanvas 를 사용하기엔 비용이 클 것 같아 임의의 값으로 처리
- 오른쪽 위치 - (글자 길이 * 폰트크기 +  x ) = 134  가 되도록. x 조정.
> [#140] 일본어일 경우 초시계 위치가 오른쪽으로 많이 들어가 있어 글자 길이로 읽도록 수정.

- src/class/container.js
초시계 블럭 삭제 로직은 해당 블럭들의 viewDestroy 이벤트에 부착되어있기 때문에
바로 오브젝트를 삭제하는 경우 각 블록의 viewDestroy 호출이 되지 않음.
그래서 오브젝트 삭제시 로직에도 초시계 블럭 삭제 로직 부착
로직 자체에 모든 오브젝트를 가져와 초시계 블럭을 사용하는 개체가 있는지 판단하고 있습니다.
> [Issue/line/248] 초시계 블럭을 가진 오브젝트가 바로 삭제된 경우 초시계 삭제로직 수행처리

- extern/util/static_mini.js
- 일반형 하드웨어 개선 사항 반영 후 교과형에 수정을 하지 않아
순서가 틀어진 문제 발생 -> 수정
> [feature] 교과형 하드웨어 버튼의 순서 변경

- src/class/engine.js
init() 옵션에 따라 재시작/시작 버튼이 동작되도록 하는기능..확인필요
1 강의 워크 스페이스
- 학습완료, 학습완료 버튼 클릭시 완성작품 팝업에서 시작-> 일시정지시 재시작 버튼이 나타나지 않던 부분 수정
- engine.js > this.buttonWrapper 값있는 경우에는 재실행 버튼이 removeClass 되지 않도록 분기처리
https://oss.navercorp.com/entryline/web/issues/741
> Issue/line/442 학습완료 작품에 대한 재시작 버튼기능 추가

- src/class/engine.js
[#11027] mac safari 에서도 ios모바일과 같이 사용자 이벤트 발생이후에 소리가 나도록 되어 toggleRun시 emptysound를 실행시키도록 수정.
> issue 11027

- src/class/scene.js
- 스테이지 선택 시 리스트 업데이트의 필요성이 애매한 것 같아 (오브젝트가 비었을 경우에만 작업하기 때문) 주석처리.
> [#line/382] 빈 리스트일 경우 다음 스테이지로 넘어가지 못하는 현상.

- src/command/commands/playground.js
> [#11161] 특정 오브젝트에서 사용하는 변수 선택시 변수를 사용하는 블럭을 다른 오브젝트에 복사 붙여넣을 경우 오류.

- package-lock.json
- package.json
- yarn.lock
Security alert: https://github.com/entrylabs/entryjs/network/alert/yarn.lock/serialize-javascript/open
- uglifyjs 는 버전에 문제가 없을 수 있으나 일단 사용처이기 때문에 업그레이드
- 실제로 2.1.1 버전을 사용하는 라이브러리는 webpack#terser-webpack-plugin -> 2.1.2 로 올림
> [security] serialize-javascript

- src/class/hw.ts
- 로직 자체 개선
- http 프로토콜 혹은 파일시스템 위에서 동작하는 경우, 로컬호스트를 최우선 연결시도
- 오프라인 프로젝트에서 https 연결 시도가 다 끝난 후 로컬호스트 연결시도함
- 오프라인은 로컬호스트기 때문에 이 대기시간동안 유저입장에서는 어찌할 도리가 없음
> 하드웨어 소켓 연결 로직 개선

- src/playground/block_view.js
타블렛으로 Longpress 동작시 ContextMenu가 나오지 않는 버그 수정
> Longpress 로 right button 동작 안되는 이슈 수정

- src/class/pixi/atlas/PIXIAtlasHelper.ts
https://oss.navercorp.com/entry/Entry/issues/11333
특정작품 부스트 모드 실행불가 관련 수정 
1. 저장된 작품 이미지 사이즈가 정수가 아닌 소수로 저장된 작품에서 발생. 
-  PIXIAtlasHelper.ts 이미지 사이즈 조회시 소수점을 정수로 처리되도록 방어코드 추가​
-  const w = pic.dimension.width | 0;
-  const h = pic.dimension.height | 0;
2. prettier 적용
> Issue/11333 특정작품 부스트 모드 실행불가 관련 수정 

- src/playground/field/block.js
문제의 출발은 commands/block.js#destrodyBlockBelow 커맨드에서 부터입니다.
재현조건은 아래와 같습니다.
- 값블록을 드래그해서 바로 삭제 (destroyBlockBelow)
- 값블록을 블록조립소로 빼는 것은 상관이 없습니다. (separateBlock)
로직 플로우는 아래와 같습니다.
- 커맨드발생
- block#doDestroyBelow#destory
- block.js#L440 (in destroy function)
문제는 아래와 같습니다.
- 해당 라인의 로직이 _setValueBlock 을 호출하는데, 이때 새 값블록뷰가 만들어짐
- 이때, 기존의 값블록뷰가 삭제되는 로직이 없음 (덮어씌워짐)
- 이 상태에서 다른 값블록을 합치기 하면,  마지막에 만들어진 블록뷰는 정상적으로 지워지나 연결이 끊어져 뷰만 남은 값블록이 아직 남아있는 상태가됨
참고사항은 아래와 같습니다.
- spliceBlock 이 뭘 의미하는지 알수없으며, 왜 블록 클래스에도 존재하는지 알수없음 (변수명으로 보면 의도한 로직은 아닌 것 같음)
- block#destory 에서만 불리는 함수
- 근데 없어도 잘돌아가는데.. 어떤 영향을 줄지 모르겠음. 또한 FieldOutput 에도 이 로직이 있음. 이쪽도 문제가 발생할 여지가 있음
주석만으로 처리한 이유는 아래와 같습니다.
- spliceBlock 에 대한 처리가 실제로 유효한지 잘 모르겠습니다.
- 이 함수 자체가 삭제되는데 있어 다른 로직들에 방어로직을 전부 넣고, 로직을 정리해야하는지 알수가 없습니다.
- 만약 정리되어야 한다면, …
> [issue/11302] 값블록을 바로 드래그 -> 제거하면 값블록뷰가 중첩되던 문제 수정

- src/playground/block.js
- destroyBelow 커맨드가 아닌 destroy 커맨드로 처리시,
블록이 완전삭제 되었음에도 valueBlock 을 새로 업데이트 해주지 않아 빈공간으로 보이는 문제수정
> [issue/11459] issue/11302 의 사이드이펙트 처리

- .eslintrc
- src/class/function.js
- src/class/variable_container.js
- src/util/utils.js
clearProject 시 함수편집모드의 문제 발생하던 문제를 수정하였습니다.
- clearProject -> loadProject 시 함수 편집모드의 함수인자블록들이 나오지 않던 문제
- 편집모드에서 clear -> load 로 새 프로젝트 시작한 경우 함수편집모드가 더이상 안열리던 문제
- edit 모드 플래그를 그대로 둔 상태로 초기화되어버리기 때문에 문제 발생
- endEdit 함수를 통해 함수편집모드 종료 후 refresh 하도록 설정
---
- 문제가 여태 발견되지 않았던 것은, Entry web 이 새프로젝트 = 페이지 refresh 이기 때문
- 관련 파일들 lint 적용 (private method 는 적용하지 않았습니다. 린트가 자꾸 잡아서 일단..)
- Entry.Func 클래스화
- Entry.Func 는 instance 와 Entry.Func 에 함수를 붙여 쓴 코드를 혼용하고있어서 static 처리했습니다.
> [issue/11416] Entry.Func 클래스화 및 clearProject 시 문제발생 이슈 수정

- webpack_config/common.js
video.worker.ts에서 사용하는 face-api.js에서 fs에 대한 warning을 supress하기 위해 fs를 webpack 에서 제거
> [비디오 블록] fs Warning supress

- package.json
- src/class/hardware/hardwareSocketMessageHandler.ts
- src/class/pixi/atlas/PIXIAtlasManager.ts
- src/class/pixi/atlas/SceneBins.ts
- src/playground/skeleton/basic/basic_text.ts
- src/playground/skeleton/basic/basic_text_light.ts
- src/util/videoUtils.ts
- yarn.lock
- 이제 개별 함수별 import 를 지원하네요
- 트리쉐이킹으로(?) yarn dist 결과물의 entry.js 파일의 용량이 12.3 -> 11.7MB 만큼 줄었습니다
> [feature] typescript @types/lodash 업데이트

- src/class/DataTable.js
> [DataTable] modalChart props 이전 전달 방식으로 수정

- src/textcoding/parser/core/text/pyToBlock.js
[#9429](https://oss.navercorp.com/entry/Entry/issues/9429)
> [#9429] 파이썬 변환시 arith 와 string concat 차이 구별 수정

- src/playground/blocks/block_ai_utilize_video.js
비디오블럭의 명세가 잘못되어있는 부분을 수정하였습니다. 
해당 블럭은 기존의 모델이 로드 되었는지에 대한 판단 여부를 나누던 블럭이었으나, 
해당 블럭의 필요성이 사라지게 되었으며, 블럭의 사용성 및 설명이 모호해짐에 따라 
모델이 인식을 1 이상 한 경우에 대해서 참을 반환하는 것으로 변경하였습니다. 
(비디오 블럭내의 " **%1 인식이 되었는가** "  블록)
> 비디오블록 명세 오류 수정

- src/playground/blocks/index.js
라인 WS 로딩 이슈 수정 입니다. entryjs가 다시 빌드 되면서 올라가서 생기는 문제로 보입니다. 라인에서는 AI 관련 컨텐츠가 없어서 다국어쪽에서 없는것을 코드 에러로 잡아서 생기는 이슈입니다.
> 라인 WS 로딩 이슈 수정

- src/playground/blocks/hardware/block_hasseam.js
초음파센서의 포트 초기값 각각 변경
trig 16, echo 17
> [하쌤보드] 초음파센서 핀번호 초기값 변경

- src/util/utils.js
오브젝트가 없을 때 나의 보관함에서 블록을 가져올 경우 에러대신 토스트를 보여줍니다.
> 보관함 블록 방어코드 추가

- src/util/utils.js
[#2949](https://oss.navercorp.com/entry/entry2/issues/2949)
이전에 pixi 5 로직을 revert할때 복원된 코드가 다시 5적용할때 빠지지 않아 오류 발생
> 이슈 2949 처리

- src/class/dialog.ts
- src/class/entity.js
- src/playground/block_view.js
[#2427](https://oss.navercorp.com/entry/entry2/issues/2427)
> 이슈 2427 처리

- src/css/components/board.less
> z-index 수정

- src/class/engine.js
[#4082](https://oss.navercorp.com/entry/entry2/issues/4082)
작품상세 의 경우 iframe으로 실제 이벤트는 iframe -> window에 mousemove이벤트가 걸려있으니
fullscreen이 되면서 iframe밖으로 나오면서 window.top 부분에는 mousemove 이벤트가 없어서 실제로는 이벤트 처리가 안됨.
이때 처리방법에는 fullscreen방식을 현재 방식에서 iframe을 전체로 팝업화 하는 방식과
현재 처리한것처럼 이벤트를 강제로 dispatch 하는 방식이 있는데 각각 장단점이 있어 고민이 되는 지점.
> 이슈 4082 처리

- src/playground/blocks/block_text.js
- src/textcoding/parser/core/text/pyToBlock.js
- src/textcoding/static/codeMap.js
[#4219](https://oss.navercorp.com/entry/entry2/issues/4219)
- 글상자 일부 블록 엔트리파이썬 모드 syntax 오류 수정
- 엔트리파이썬 모드에서 실행/정지 시 글씨체 설정이 None 으로 변경되는 오류 수정
> [#4219] 엔트리파이썬 모드 일부 글상자 블록 실행 오류 수정

- src/class/DataTable.js
[#4466](https://oss.navercorp.com/entry/entry2/issues/4466)
- props말고 data에 정보를 넣어 보냄
> [DataTable] 차트가 2개 이상일 때 먼저 연 차트로만 조회되는 현상

- src/playground/blocks/block_looks.js
- src/playground/scope.js
[#2096](https://oss.navercorp.com/entry/entry2/issues/2096)
해당 위치에 getNumberValue || 0 으로 할까하다가 getNumberValue의 리턴하는 쪽에서 처리했습니다
> [#2096] 오브젝트 상태 변경 시 숫자가 아닌 값을 입력하면, 오브젝트의 크기가 비정상적으로 변경 

- src/playground/block_view.js
[#4557](https://oss.navercorp.com/entry/entry2/issues/4557)
드래그로 선택한 블럭의 magnet을 가져와 검사하기 때문에 발생한 issue.
thread의 마지막에 달린 블럭을 가져와서 검사하도록 수정
> [#4557] 끝 블록을 포함한 블록 묶음을 다른 블록에 조립하면 WS프리징

- src/playground/block_entry.js
- src/playground/blocks/block_calc.js
- src/textcoding/parser/core/block/blockToPy.js
[#4352](https://oss.navercorp.com/entry/entry2/issues/4352)
- 엔트리파이썬 모드에서 나머지 계산 dropdown이 노출되지 않는 오류 수정
- 괄호 제거 정규식 패턴 오류 수정
> [#4352] 엔트리파이썬 모드 계산 > 몫, 나머지 블록 오류 수정

- src/textcoding/static/keyboardCode.js
[#4347](https://oss.navercorp.com/entry/entry2/issues/4347)
파이썬모드에서 ascii를 직접 입력하는 경우 대응을 위해 추가된 키 값 중 
8(Backspace), 9(Tab)가 기존 키와 중복되어 정상적으로 동작하지 않아 제거 처리
> [#4347] 엔트리파이썬 모드 keyboardCode map의 충돌 key 제거

- src/class/engine.js
- src/class/function.js
- src/core/promiseManager.js
금일 코드리뷰하였던 Entry.engine.isContinue 관련 함수들 삭제하였습니다.
삭제한 함수는 아래와 같습니다.
- src/class/engine.js > function.executeFunction(threadHash) 에서만 사용
- src/class/function.js > executeFunction(threadHash) : 사용처 없음
- src/core/promiseManager.js > sleepWithPause(time, blockId) : 사용처 없음
> Entry.engine.isContinue 관련 함수 제거

- src/class/object.js
[#4827](https://oss.navercorp.com/entry/entry2/issues/4827)
- 우측 클릭 시에도, 오브젝트 관련 메뉴 노출
> [4.14.0][#4827][object] 오브젝트 이름 영역에 우측 클릭 시, 오브젝트 이름 수정이 가능한 현상

- src/textcoding/parser/core/block/blockToPy.js
[#5034](https://oss.navercorp.com/entry/entry2/issues/5034)
- 함수 파라미터 이름 변환 오류 수정
- 함수 statement와 블럭 statement의 텍스트 코드 변환 로직 동일하게 변경
> [#5034] 함수 파라미터 사용 중에 파이썬 모드로 전환 시 코드 변환 오류 수정

- src/graphicEngine/GEHelper.ts
- src/util/videoUtils.ts
[#5333](https://oss.navercorp.com/entry/entry2/issues/5333)
1. 초기 stream의 track을 stop시켜서 항상 동작을 보장하도록 처리
2. GEHelper destroy을 추가
> 이슈 5333 추가 이슈 처리

- src/playground/block_menu.ts
[#5391](https://oss.navercorp.com/entry/entry2/issues/5391)
1. 블록의 skeleton이 button, text 일경우 조립소에 추가하는 기능 제거
> 이슈 5391 처리

- src/class/function.js
[#5655](https://oss.navercorp.com/entry/entry2/issues/5655)
> cancelEdit 할때 generateWsBlock에서 restore하지 않도록 처리

- src/playground/blocks/hardware/block_iCOBOT.js
>  Change the icobot_get_discomfort_index_value

- src/class/hw.ts
- types/entry.d.ts
https://oss.navercorp.com/entry/entry2/issues/5760
@leunge 
#2266 PR은 제거해 주셔도 될 것 같습니다.
> [5760] 하드웨어 최소버전안내문구 entrylms => modal로 변경

- src/class/container.js
- src/class/engine.js
- src/class/helper.js
- src/class/object.js
- src/class/playground.js
- src/class/toast.js
- src/css/components/playground.less
- src/css/components/toast.less
- src/playground/block_menu.ts
- src/playground/blocks/block_expansion_festival.js
- src/util/htmlElementPatcher.js
- src/util/utils.js
- types/index.d.ts
[#5905](https://oss.navercorp.com/entry/entry2/issues/5905)
> 이슈 5905 처리

- src/playground/blocks/hardware/block_roborobo_robokit_rs.js
내부 입력값 드롭다운에서 블록 형태로 변경 및 관련 부분 수정
> Dotmatrix 블록 형태 변경

- src/playground/blocks/hardware/block_iCOBOT.js
- Buzzer 부분에서 중복으로 데이터 처리가 되는 부분이 있어 엔트리 쪽 코드를 제거하였습니다.
> [20230321]Remove the Buzzer Time Off Code

- src/playground/blocks/hardwareLite/block_microbit2_lite.js
- https://oss.navercorp.com/entry/entry2/issues/6150
> [#6150] 마이크로비트2 웹연결 센서값 오류 수정

- extern/face-landmarker.worker.js
- src/util/mediaPipeUtils.ts
[#7149](https://oss.navercorp.com/entry/entry2/issues/7149)
1. human state가 최소 idle이 한번이라도 불린 상태에서 부터 인식 진행되도록 수정 처리
2. restart 되는 과정이 명확하게 stop 상태 이후로 변경
> 얼굴 인식 블록 이슈 처리

- src/playground/blocks/hardware/block_handino.js
손가락 천천히 동시, 하나씩, 접기, 펴기 [매우 천천히, 천천히, 보통, 빠르게] 기능 추가 
약속, 브이 제스처 추가|
+ 블록 명세 일부 워딩 수정 (영어 -> 한국어)
> 핸드이노 기능 추가

- src/playground/blocks/hardware/block_jinirobot_toybot.js
지니로봇 ToyBot 블록 수정
1. ToyBot 서보모터 드랍다운 목록에서 속도를 4까지로 제한하였습니다.
> ToyBot 서보모터 속도 수정

- src/playground/blocks/hardware/block_arduino.js
- src/playground/blocks/hardware/block_arduino_ext.js
- src/playground/blocks/hardware/block_arduino_nano.js
https://oss.navercorp.com/entry/entry2/issues/8497
> 아두이노 다국어 수정

- src/playground/blocks/hardware/block_robotis.js
- src/playground/blocks/hardware/block_robotisRBKoala.js
- src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js
- 로봇아이 블록 형태 수정
- 로봇아이 블록 추가
- 코알라봇 블록 기능 수정
> 로봇아이 블록 수정/추가

- src/playground/block.js
- src/textcoding/parser/core/block/blockToPy.js
> 이슈 8675 처리

- src/playground/blocks/hardware/block_robotisRBPracticalAssembly.js
- src/playground/blocks/hardwareLite/block_robotis_robotai_lite.js
- 로봇아이 AI Camera 모드 순서 변경(표정 인식을 2번째로 이동)
> 로봇아이 AI Camera 모드 순서 변경

- src/playground/blocks/hardware/block_zumiMini.js
> 주미 미니 블록 수정

- src/class/hw_lite.ts
- src/playground/blocks/hardwareLite/block_microbit2_lite.js
- src/playground/blocks/hardwareLite/block_microbit2ble_lite.js
- types/index.d.ts
https://oss.navercorp.com/entry/entry2/issues/8755#issuecomment-15199876
> [#8755][하드웨어] 마이크로비트 firmwareFlash 지원여부 속성추가

- src/playground/blocks/hardware/block_microbit2.js
- src/playground/blocks/hardwareLite/block_microbit2_lite.js
- src/playground/blocks/hardwareLite/block_microbit2ble_lite.js
https://oss.navercorp.com/entry/entry2/issues/9025#issuecomment-16001631
> [#9025] 마이크로비트 다국어 수정

- src/playground/blocks/hardware/block_whalesbot_eagle_1001.js
- src/playground/blocks/hardwareLite/block_whalesbot_drone_lite.js
Changelog:
- add speak blocks
- fix language
> fix speak block, fix language

- src/playground/blocks/hardwareLite/block_robotis_robotai_lite.js
> 로봇아이 lite 블록 문구 수정

- src/playground/blocks/hardware/block_robotis.js
알쥐, 알라, 꼭두 로봇의 경우 write 블록 실행후 Entry.hw.portData 초기화를 하지 않음.
> Entry.hw.portData 초기화 조건 수정

- src/playground/blocks/hardware/block_ITPLE_board.js
잇플보드를 학습하는 저학년이 사용하기 쉽게 기존의 핀번호가 있는 블록을 핀번호가 보이지 않는 블록으로 교체하였습니다.
> 저학년을 위한 쉬운 블록 생성
